### ISSUE TITLE
Wishlist: Copy to clipboard

### ISSUE THREAD

**Issue by adriglib** [kepi/chromeEyeDropper#101]
Press twice on the name (rgb, hsl etc.) to copy the value to clipboard.

**Comment by kepi** [comment]
Thanks, I like the idea. I'll try to add it when I find some time.

**Comment by darthwalsh** [comment]
Yes, this would be cool!
It might be even more useful if using the eyedropper automatically copied the FF00FF to clipboard :)
(But I guess then you'd need to select which format you want.)

**Comment by kepi** [comment]
> It might be even more useful if using the eyedropper automatically copied the FF00FF to clipboard :)
(But I guess then you'd need to select which format you want.)

This is already thing :) Maybe even default. Just head to option and there you can choose that after picking rgb format of color is copied to clipboard (with or without #)
