### ISSUE TITLE
Eydropper has crashed & Something went wrong with Chrome

### ISSUE THREAD

**Issue by noahneng** [kepi/chromeEyeDropper#102]
Hi, as soon as I open up Chrome, I get an icon that says:
"Eye Dropper has crashed. Click this balloon to reload the extension."
At the same time, Chrome does not open, instead I get a page that reads:
"Aw Snap!
Something went wrong while displaying this webpage."

So I thought these two issues might be related. Any idea has to how to resolve the problem? Nothing opens up in Chrome, so I can't adjust chrome settings or extensions.

**Comment by kepi** [comment]
Hi, sorry to hear that. Extensions are isolated from chrome so I they shouldn't be able to crash chrome in any way.

I think it would be unfortunately other way, that there is some problem in Chrome itself.

I can't supplement Chrome support but you can try backup your current chrome profile and then delete all extensions in it (see https://www.chromium.org/user-experience/user-data-directory). You should be able to delete all content in Extensions directory.

Be sure to check other possible problems like lack of free space on your computer hard drive or not restarted computer after some huge system updates.
