### ISSUE TITLE
inaccurate color picked after scrolling

### ISSUE THREAD

**Issue by df0o** [kepi/chromeEyeDropper#104]
scrolling down page results in incorrect colors being previewed and picked

**Comment by kepi** [comment]
Thanks for this report. Can you please give me some specific page on which you see this problem? Even if it is on "all pages", please pick some on which I can easily test it.

Give me also more details about your environment - operating system and ideally chrome version.

**Comment by gkarapeev** [comment]
Same issue here. The picker only works correctly if I haven't scrolled down at all, in other words, if I'm at the very top of the page. I'm using **Chrome 77 on macOS (Mojave)** and I'm looking at an Angular single-page web app.

**Comment by kepi** [comment]
@gkarapeev thanks for information. Can you please send me URL to that angular page you tested on? Or any other page where you see that problem. Thanks.

**Comment by kepi** [comment]
I believe this problem has been finally fixed with 0.5.4 version released yesterday. Feel free to repoen the issue if it didn't fix it for you.
