### ISSUE TITLE
All my collors have disappeared  

### ISSUE THREAD

**Issue by leberika** [kepi/chromeEyeDropper#106]
What to do?

**Comment by kepi** [comment]
Is it possible that you used "Trash colors" function? There is no undo for that unfortunately.

In case you are using Plus features, can you check if you didn't switch color palette? You should see "Palette: default" in popup. If you see anything else, you can use palette switch icon next to name of palette and there may be your dissapeared colors.

If neihter of this is true, can you describe when you lost your colors? Was there some update or did it happen during work?

**Comment by leberika** [comment]
Hi there,

Thanks so much for your prompt reply.

One day the colors were there, the next they weren’t. I noticed this 
about three days ago. They are in my Chrome browser. I don't know if it 
is connected to an update or what. There were about 40 saved colors.

This is not a matter of life and death certainly, but if you know how I 
may retrieve them, I would be grateful.

Thanks,
Robert

------ Original Message ------

**Comment by kepi** [comment]
So palette is "default"? One of things which may be wrong is palette switching code.

If you can work with chrome's developer console at least a little, following may help to get some info:

1. go to menu -> More tools -> Extensions
2. check checkbox Developer mode
3. find eye dropper between extensions
4. click on Inspect views: `background.html`
5. switch to `Console` tab

There should be some info and no error. If you see any error, please past it here. 

you can try couple javascript commands there (just write them in console) and send me output:

1. `bg.history`
2. `bg.history.palettes[0]`
3. `bg.hsitory.plaettes[0].colors`

would be probably great to create some page which will show more info in some view

**Comment by leberika** [comment]
I so appreciate your time and energy on this. I think I am in over my 
head here. I know some HTML and CSS and can put a web page together, but 
this will be beyond me. I think I just have to re-build my color library 
and chalk it up to ???

Again, thank you so much and all the best,
Robert

------ Original Message ------

**Comment by hrhageman** [comment]
All mine just disappeared, too...

**Comment by hrhageman** [comment]
Here's my developer console:
![image4493](https://user-images.githubusercontent.com/31785938/30236432-5e097664-94d6-11e7-8828-f14971de6f5f.png)

**Comment by kepi** [comment]
Ok, I see where I made the error.

For both of you I hope this will work:

1. open popup window
1. click `Unlock Plus` button in left bottom corner
1. choose free option and unlock Plus version
1. open popup window again
1. next to "Palette: default" is icon now to switch palettes. Click on it and you should see palette named `converted` with all your missing colors, just click on it.

I'll try to release fix for this today so others don't have same problem. Steps above should fix it for you too.

**Comment by kepi** [comment]
Fixed version will be in Chrome Store in about hour so you can wait for update.

Thanks both of you for reporting and helping with investigation.

**Comment by leberika** [comment]
Thank you! Very kind of you to address this so quickly..

------ Original Message ------
