### ISSUE TITLE
Color Picker only showing black

### ISSUE THREAD

**Issue by ericae07** [kepi/chromeEyeDropper#109]
https://rothys.com
Either shows as black or white, or the hover is not accurate. 

Chrome

Some other pages work fine.

**Comment by kepi** [comment]
Thanks for report. Can you please specify which operating system do you have?

Also can you try to open start picking from page and while picking, press `u` key? It should reload for second or two and then continue picking. Let me know if it remains same (wrong color or black/white) or if it helps.

**Comment by ineedcolors** [comment]
I am having this same issue.  It was working just a few minutes ago, then all of a sudden it started doing the black/white/inaccurate pick thing.  I tried restarting the browser, clearing the cache, etc.  I need this to function so I can finish some work.  Help, please!

**Comment by kepi** [comment]
@ineedcolors please give me information about operating system, chrome version and page you are trying it on.

Also please try approach I described above (with `u` key).

you may try enable extension in anonymous browser window and try it there, but don't think it can do something.

It seams to me there can be some problem caused by chrome update or OS update, especially when it worked for you before.

**Comment by jbreed** [comment]
Having the same issue here on my Macbook within Chrome. Initially I used this plugin perfectly on my Windows machine with no issues to find it to be faulty on the macbook. The dropper icon doesn't show in place of the mouse icon, but the mouse icon on screen does have a black box next to it.

**Comment by kepi** [comment]
@jbreed thanks for info. Can you please explain what are you meaning by "icon dropper"? Do you mean cursor or something else? If you are able to make video of your screen, it would be amazing.

Also thanks for confirming that it is better in more recent chrome version, I was hoping it would be the case.

**Comment by jbreed** [comment]
It appears the plugin is not working again. It works if I don't scroll down the page, but if I go lower on a page I just get a black square.

In reference to the dropper, yes I am referring to the cursor icon. This really doesn't matter as long as it still functions.

**Comment by kepi** [comment]
@jbreed thanks, it can be problem in scroll update function, thats at least something to chase for. Can you please try manually update colors? Default shortcut is `U` if you didn't change it in options. Simply scroll and when you see black instead of color, hit the shortcut, wait untill spining weel dissapears (should be less then second) and than check if colors are appearing ok.

Thanks

**Comment by jbreed** [comment]
@kepi I am seeing the same results while using the shortcut 'u'. I do see the reload icon display, but ends with the same results of black only.

**Comment by kepi** [comment]
@jbreed thanks for update, I'll try to find someone with Mac next week and dig into this. I hope I'll be able to reproduce it.

**Comment by kepi** [comment]
@jbreed one more question. Is problem present on all pages or it is working somewhere? Would be great if you can past here one address where it isn't working for you, thanks.

**Comment by tb9jen** [comment]
I also have this problem. I'm on a Mac,0.13.3 and using the latest version of Chrome.  Occasionally the picker works, but most of the time it shows solid black for the entire page, on any page.

**Comment by sega21** [comment]
вс, 18 марта 2018 г., 16:15 tb9jen <notifications@github.com>:

**Comment by mishra93mohit** [comment]
I'm also facing the same issue. It shows only either black or white. Issue has been opened for a long time. Is there any fix for it?

**Comment by kepi** [comment]
No fix currently, I'm having hard time to find someone with Mac to reproduce :/

**Comment by mishra93mohit** [comment]
I'm using Windows. So I don't think it's platform specific.

**Comment by mishra93mohit** [comment]
I don't know what happened...but removing the extension and adding it again did the trick for me. It's working for me

**Comment by kepi** [comment]
Can anybody confirm that removing and readding extension can help? I think that windows problem was different than Mac one, but maybe...

**Comment by fairliereese** [comment]
Reinstalling didn't work. I think that the problem may have something to do with scrolling. For reference, I'm trying to pick from http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/ this page and have to scroll down to get to my colors (though it doesn't work).

**Comment by PwntasticKev** [comment]
Just recently ran into this issue. reinstalling has not worked either. stopped working after mac update.

**Comment by JohannesRegner** [comment]
I have the same issue, with newest Chrome and Windows 10. Reinstall didtn work

**Comment by digren-tech** [comment]
Use another "extensionzilla" for this and it was always picking up black until I turned off "Play HDR Games" in Display Settings (Win10) and it has worked since. Verified turning HDR on and off works. Might work for this one. Hope it helps ;)

**Comment by kepi** [comment]
I'm really sorry this took so long time, but issue should be finally fixed in version 0.5.4. New version is already published in Chrome Store and should be auto updated in your browser.
