### ISSUE TITLE
Identify the font-styles

### ISSUE THREAD

**Issue by overslept5d** [kepi/chromeEyeDropper#110]
It will be GREAT for a our web developers if your tool can also identify the font styles.

**Comment by kepi** [comment]
I think this is out of scope of this extension and I don't want it to get bloated. But it is tempting as I can use such functionality myself :)

I'm really not sure if I have time for this or if it is even doable, but not rejecting the idea just yet. Developer tools have to be enough for now.

**Comment by kepi** [comment]
I'm definitely rejecting this as it is ouf of scope of this extension. I really think it would be usefull, but it would clutter the UI too much.
