### ISSUE TITLE
Color picker not visible if a site has a  tawk script.

### ISSUE THREAD

**Issue by mwangikinuthia** [kepi/chromeEyeDropper#111]
The color indicator is not able to float over other floating elements generated by javascript.
![tawk_git](https://user-images.githubusercontent.com/9838419/33220720-7e18495a-d15b-11e7-9fb7-9b7f4ccdf1cd.png)

**Comment by kepi** [comment]
This was fixed in latest release (0.5.10) hopefully. Sorry it took so long :/
