### ISSUE TITLE
hsl() color display is incorrect format

### ISSUE THREAD

**Issue by jakeparis** [kepi/chromeEyeDropper#115]
In the popup display, the hsl() formatted colors are displayed as three integers with no units: 
  `hsl(210, 25, 80)`
However, this is an invalid format. The second two parameters have to have the percentage unit included like so:
  `hsl(210, 25%, 80%)`

**Comment by kepi** [comment]
Thanks, wasn't aware of that. I'll fix it with next update.

**Comment by kepi** [comment]
Thanks again for report, this is now fixed in latest version.
