### ISSUE TITLE
Doesn't work at all for sampling images in Chrome 69

### ISSUE THREAD

**Issue by jcollum-nike** [kepi/chromeEyeDropper#121]
Chrome 69, OSX 10.13.6 

Installed 5 minutes ago. 

1. Select "Pick Color from Web Page" 

1. Run the pointer over this image

![image](https://user-images.githubusercontent.com/40277227/47111388-3f65af00-d208-11e8-9370-9c845278ce86.png)

Expected: colors change

Actual: all pixels register as black

The odd thing is that I can sample the image successfully on the github page but not on a webpage running from the server on my local machine. But since I need it for a local web page, well...

Also worth noting that Chrome's developer tools eye dropper works fine

**Comment by kepi** [comment]
What is exactly address of page you are trying it on on your local computer? I just tried http://localhost with some port and it is working without any trouble, but it may be possible that chrome is blocking some local requests.

Also - do you have image in some web page or you are displaying only image in browser?

**Comment by jcollum** [comment]
Can't recreate it today so I'll close.
