### ISSUE TITLE
Can't Pick from Google Forms 

### ISSUE THREAD

**Issue by sophiaberger** [kepi/chromeEyeDropper#122]
Similar to another user with a similar problem, I can't select a color within Google Forms. Works fine on a different site (colourpop.com). I'm specifically trying to select a color from an image within the form, but the cursor isn't quite accurate. Here's a screenshot to show you what I mean:

<img width="207" alt="screen shot 2018-11-27 at 7 15 57 pm" src="https://user-images.githubusercontent.com/10731721/49120003-eb270380-f278-11e8-89b9-52ac5eba351d.png">
<img width="209" alt="screen shot 2018-11-27 at 7 15 51 pm" src="https://user-images.githubusercontent.com/10731721/49120005-eb270380-f278-11e8-9f5f-ff0f1c889f96.png">
<img width="175" alt="screen shot 2018-11-27 at 7 15 43 pm" src="https://user-images.githubusercontent.com/10731721/49120006-eb270380-f278-11e8-857d-19290a0941e8.png">

Forgot to add - Chrome up to date as of just now, Version 70.0.3538.110

**Comment by kepi** [comment]
Would it be possible to send me link to this form so I can try to reproduce? I tried to create new google form, added some pictures and so far it is working OK. Please let me know what operating system do you use too so I can test in similar environment.

**Comment by kepi** [comment]
I belive this was fixed in version 0.5.4. Feel free to reopen or create new issue if not.
