### ISSUE TITLE
0.5.2: no way to change shortcut

### ISSUE THREAD

**Issue by jcollum-nike** [kepi/chromeEyeDropper#124]
![image](https://user-images.githubusercontent.com/40277227/49622627-34650a80-f97f-11e8-86e3-1df9c1ffeac2.png)

Extension page: 

![image](https://user-images.githubusercontent.com/40277227/49622658-4e065200-f97f-11e8-9381-251d56b6b57a.png)

Selecting "Extension options" just takes me back to the first page. I don't see any link to change shortcut on that page. This tool is conflicting with another tool I use more often so I will have to disable this tool until this is fixed.

**Comment by kepi** [comment]
Sorry for late reply - I simply don't now how to get notifications from github working and I didn't know there is open issue :/

I have to update description in options page as Google is constantly changing layout of their settings.

You should be able to simply type `chrome://extensions/shortcuts` into URL to get to shortcuts settings now. Is it working for you?

**Comment by kyleplays** [comment]
> You should be able to simply type `chrome://extensions/shortcuts` into URL to get to shortcuts settings now. Is it working for you?

The insider version of edge (it's being redesigned) runs on chromium and you have to type `edge://extensions/shortcuts` rather than `chrome://extensions/shortcuts`, so it's different. But after fixing that, it works fine.
