### ISSUE TITLE
Custom Palettes 

### ISSUE THREAD

**Issue by ghost** [kepi/chromeEyeDropper#125]
Is it possible or is it on your to-do list to allow for deleting a color in a custom (or the default) palette? Would be nice to delete a color I've accidentally added.

Also is it possible for you to program the last-used palette to remain visible vs. it dropping back to the default palette? 

Thanks

**Comment by kepi** [comment]
Deleting color is something I definitely want to implement as I need it too :)

As for last-used palette, it is working for me like that. What behavior do you see? Can you please describe exact steps so I can try to reproduce?

**Comment by rgnbgn** [comment]
+Upvote, an plans for this?

**Comment by kepi** [comment]
Sorry, but no ETAs, it would be empty promises which I can't hold on to. I can only confirm that I really want to do this and it is relatively high in ED priorities.

**Comment by kepi** [comment]
Removing colors will be possible in the next version, which should be alive at the start of next week.

**Comment by kepi** [comment]
Removing colors has been implemented for some time.

Last used palette IMHO worked before, but will definitely work in next version, which is completely rewrite and always store last used palette.
