### ISSUE TITLE
Can't choose color in Google Forms

### ISSUE THREAD

**Issue by astrolasher** [kepi/chromeEyeDropper#126]
While in google forms everything is black when trying to pick a color.

**Comment by kepi** [comment]
Can you please provide more information about your Operating system and Chrome version? I don't see any problem on my computer so I need to dig deeper.

**Comment by iyeeta** [comment]
I'm having a similar problem. On google forms, when I select the color picker the extension closes and nothing happens.

**Comment by kepi** [comment]
I belive this issue was fixed in 0.5.4. Checked now in multiple documents and it looks ok.

Feel free to reopen issue or create new one if you hit it again, but please attach little more information.
