### ISSUE TITLE
Stop Eye Dropper from opening a new page when chrome is opened

### ISSUE THREAD

**Issue by Yohohobob** [kepi/chromeEyeDropper#128]
I love the tool... but... it annoys me greatly that a new browser page is opened every time I open Chrome.  I need Eye Dropper infrequently, so it is frustrating that it auto loads when it is not wanted.

**Comment by kepi** [comment]
Can you please be more specific about what is going on? Eye Dropper should not be responsible for opening any page on browser start. What is in that new opened browser page? Please give me also details about chrome version and your operating system so I can try to reproduce.

In any case - I took great care to not do any unnecessary autoloading - it doesn't inject any code until it is needed, only basic background process is started with chrome to handle shortcuts etc and no pages should be opened.

**Comment by al7fox** [comment]
Hi, I have the same issue. Chrome Version 80.0.3987.149 (Official Build) (64-bit) win 10. thanks.

**Comment by kepi** [comment]
@al7fox can you please be more specific? It would be amazing to attach video/screencast of what is it exactly doing or at least describe in detail what is going on. Thanks!

**Comment by al7fox** [comment]
Hi Kepi, it is very simple. Every time you open a new window in chrome, you will get the standard "new tab page" from chrome plus another tab with the Eye Dropper welcome message. 

Settings in chrome are correct (on startup "open the new tab page"). 
This is happening every single time you open chrome for the first time. if you have an active window and you open another one, then there is no welcome message. however, if you close all chrome windows/quit chrome and open a new chrome window for the first time, then you will see again the welcome message/tab.

Let me know if you need any further information. thanks.

[
![Eye Dropper](https://user-images.githubusercontent.com/63102446/78664082-391b3500-78cb-11ea-9cf5-cc0ffa26a4eb.PNG)
](url)

**Comment by kepi** [comment]
Thanks for info and screenshot. This is definitely bug and shouldn't happen under any circumstance :/

It seems that Eye Dropper either doesn't have permission to your local storage or there is some problem with your local storage.

Is color history working between Chrome restarts?

**Comment by al7fox** [comment]
Hi Kepi, 

I am not experiencing any other issue with my local storage and the color history is working fine between chrome restarts. 

I hope this helps.

thanks!

![Capture](https://user-images.githubusercontent.com/63102446/79361725-9bb0a880-7f3d-11ea-8a10-d9ef24547b8c.PNG)

**Comment by kepi** [comment]
I'm still not sure why this was happening. Anyway I found out that there is new way how to do after-install page for some time - so I switched to it. Should be fixed in version 0.5.5 which is already available in chrome store (and should be auto updated for you). Let me know, if it doesn't help.

**Comment by al7fox** [comment]
Thanks Kepi. I confirm that with version 0.5.5 I am no longer experiencing this issue. thanks for your help.
