### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by danielven00** [kepi/chromeEyeDropper#129]
Export creates CSV but it's blank.

**Comment by kepi** [comment]
Thanks for report, I can reproduce the problem and should be easy to fix.

**Comment by sebastienashm** [comment]
Same trouble. I've just paid a little bit to use it right now...

**Comment by kepi** [comment]
Finally found couple minutes, new version 0.5.3 is uploaded and should appear on Chrome Web store in couple minutes.
