### ISSUE TITLE
CIPA Compliance

### ISSUE THREAD

**Issue by Bkramer-Flatbush** [kepi/chromeEyeDropper#130]
We wanted to install Eye Dropper on our student's chromebooks and my director of IT asked me to verify that you are CIPA compliant.  
1. One of the violations of CIPA is: Unauthorized disclosure, use, and dissemination of personal information regarding minors.  Do you do that?
2. If we belong to GAFE, can I assume that all chrome ext. and google app add-ons are CIPA compliant?
3. If our student's google accounts only have their name and email address, do I really provide any "personal information regarding minors?"

**Comment by kepi** [comment]
1. Eye Dropper is not collecting any personal data at all. Only data collected are colors history which is synced through google cloud and I have no access to it.
2. Most importantly - its not up to me to say. Unofficially - It may be so for GAFE (best to check https://edu.google.com/why-google/privacy-security/?modal_active=none and/or consult with google) but some extensions are collecting personal data and may not be CIPA compliant. You have to check every one of them unfortunatelly.
3. I'm not familiar with US law so I can't answer that. In EU (which I believe hasv more strict rules) email address is considered personal information.

Anyway, I'm glad to hear that Eye Dropper may be of some use to your student.

**Comment by Bkramer-Flatbush** [comment]
Thank you for your quick and very helpful response!
_____________________
Rabbi Benjy Kramer
Yeshivah of Flatbush Joel Braverman High School
Director of Educational Technology
732-910-0243
