### ISSUE TITLE
Does not work in Chrome via WordPress site. 

### ISSUE THREAD

**Issue by eddieishere** [kepi/chromeEyeDropper#131]
Just picks black constantly.

**Comment by kepi** [comment]
Thanks for report. What operating system do you have? What specific site are you experiencing this problem on? If there are more or all, please give link at least to some so I can try to reproduce the problem.

To be completely sure - if you just installed the extension, please try to restart the browser first. In some  edge cases it might help.

**Comment by TechnicallyEclectic** [comment]
This is happening to me as well. I'm using Windows and Chrome. This is a new computer, and everything is updated.

**Comment by kepi** [comment]
@TechnicallyEclectic thanks for report. Please can you confirm that you restarted Chrome (turn it off completely and than start) after installing the extension?

I'm just trying to pinpoint the source of problem as it is working without any problem on your website in my case and I'm not exactly sure what can cause the issue.

**Comment by Naismith** [comment]
This is happening to me as well. I find this happens more often when you have content that scrolls into the page. May not be word press specific - but more with content that has been animated into the screen.

**Comment by kepi** [comment]
@Naismith thanks for your information. Can you please post examples of pages where you are hitting this problem? It would be huge help if I'm able to reproduce the problem as now I don't know where is the bug hidden. Thanks.

**Comment by kepi** [comment]
I'm really sorry this took so long time, but issue should be finally fixed in version 0.5.4. New version is already published in Chrome Store and should be auto updated in your browser.
