### ISSUE TITLE
Doesn't work at laptop

### ISSUE THREAD

**Issue by NastyaZot** [kepi/chromeEyeDropper#132]
Hey, I've been using your extension for an year at least, worked perfectly. About few months ago I've moved to work from a laptop with a screen 14", from then the eye dropper doesn't works.
If I want to drop some color it's just kinda doesn't see it, if I move mouse on an element it shows me only #ffffff color or #000000 color. 
If it helps, I've got kinda the same problem at Chrome Inspect mode's eyedropper. Chrome's dropper just doesn't work after I click on it. I think that maybe my laptop's screen size triggers some media rules at both of the extensions, like if they think that I'm trying to drop the color from a mobile.
Do you have some solution for it?
I'm using Crome Version 75.0.3770.142, Windows 10 64 bit.
![bug1](https://user-images.githubusercontent.com/43242327/61593322-c35d2500-abe6-11e9-924b-73132966d1d3.JPG)

**Comment by kepi** [comment]
Hey, do you pick white everywhere on the screen or other colors too? No matter if they are correct or not, just if it is always white?

To be sure - did you try it with all extensions but Eye Drooper disabled? It seams to me that problem may really be in your small screen, but I want to rule out other possibilities first.

**Comment by NastyaZot** [comment]
If I'm trying to pick any color from any element the eye dropper shows me it's color as #fff or #000, only two of these, or sometimes it shows me color around of the pointed place (about 50-200 pixels around), like if I'm pointing at button that has blue color, eye dropper shows me pink color of picture that placed about 200 pixels to the left of that blue button.
![bug2](https://user-images.githubusercontent.com/43242327/61594035-c14b9400-abef-11e9-9798-a25976b91bd4.JPG)


I attached screenshot, you can see there that I was pointing at "comment" button, that has green color, but in the little window you can see that it picked the color as black #000000.

The only extension I have at my chrome right now is Addblocker, but anyway, before it, when I was working on larger screen (about 22-23") it was working perfectly, so I guess that's not a problem.

**Comment by ShahoodulHassan** [comment]
In my case too, it always shows black color, no matter which color I place the cursor on.

**Comment by kepi** [comment]
I'm really sorry this took so long time, but issue should be finally fixed in version 0.5.4. New version is already published in Chrome Store and should be auto updated in your browser.
