### ISSUE TITLE
Cannot pick color from webpage

### ISSUE THREAD

**Issue by Micheleredmon** [kepi/chromeEyeDropper#134]
I am unable to choose a color from any webpage. No matter where I click it just shows black. 
![Color dropper](https://user-images.githubusercontent.com/54595570/63793340-5eb37b00-c8b4-11e9-8e7d-3efc02a3c0c9.JPG)

**Comment by kepi** [comment]
I'm really sorry this took so long time, but issue should be finally fixed in version 0.5.4. New version is already published in Chrome Store and should be auto updated in your browser.
