### ISSUE TITLE
Import Palettes (good) OR Shared Palettes Between Locations With Same Profile (better) 

### ISSUE THREAD

**Issue by BurtThaMan** [kepi/chromeEyeDropper#137]
Would be really nice if we could import our exported palettes. Or even better... our palettes need to save between locations using same profile. As it is now, if I want to work from home I'd have to reload all my palettes one at a time :(

**Comment by kepi** [comment]
Sharing palettes between same profile has been implemented for couple years now, I just probably forgot to close this.

In next version, there is improved export of palettes and I'll hopefully add import soon too.
