### ISSUE TITLE
Seletor de cores duplicado ao clicar na guia

### ISSUE THREAD

**Issue by DyogenesBrenner** [kepi/chromeEyeDropper#138]
## Duplicate color picker
- After first click
![image](https://user-images.githubusercontent.com/12235131/69160074-4e7bf800-0abf-11ea-9013-b9da1a74e03c.png)

- After the fourth click
![image](https://user-images.githubusercontent.com/12235131/69160239-9f8bec00-0abf-11ea-8b07-1129d0e4fa28.png)

**Comment by kepi** [comment]
Thanks for the report. Is it possible that you disabled automatic extension upgrades somehow? Can you please confirm you have latest version of extension? I fixed this issue already some time ago, so not sure if this regression or not. Looks ok during my tests.

**Comment by kepi** [comment]
I belive this issue is not present for long time so closing now as there is no new info.
