### ISSUE TITLE
Colours not being picked up anymore

### ISSUE THREAD

**Issue by naomihyett** [kepi/chromeEyeDropper#141]
I've been using this eyedropper tool for several months and it's never let me down. Most recently, it seems to have stopped working and will only show me the colour black or white, no matter what I hover over.

**Comment by kepi** [comment]
Thanks for report. Could you please give me more information about your environment? What operating system are you using? Do you have stable Chrome, what version?

Please send me also URL of web page where you have problem. If the problem is on every site, just pick one and let me know so I can test.

**Comment by chul1ta26** [comment]
I am having the same problem.  I'm using IOS version 10.15.3, Crome Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by Pat12340** [comment]
I am also having the same issue as @naomihyett. To add more detail, I can get the eyedropper to work perfectly in my Trello account when picking a color from the background image. 
Chrome version: Version 80.0.3987.149 (Official Build) (64-bit)
Windows Version	10.0.17763 Build 17763

**Comment by kepi** [comment]
So far I haven't been able to reproduce the problem. Unfortunately I don't have IOS available, but @Pat12340 is reporting similar/same problem on Windows, where I can test later this weekend.

**Comment by hannahcarroll** [comment]
I'm having the same issues on Windows 10 running Chrome Version 80.0.3987.149. I get either black or white.

Here's a website I was trying to choose colors from if this helps: https://bhaskarvk.github.io/colormap/

**Comment by kepi** [comment]
Thanks @hannahcarroll for detailed report, this is exactly what I need. Anyway it is really weird as with exact same setup (same chrome build, windows 10) it is working well for me.

Would you please be so kind and try Eye Dropper in anonymous mode, so we can rule out interference with other extension?

1. go to chrome://extensions page (or Settings -> Extensions)
2. click on *Details* in *Eye Dropper* box
3. click *Allow in incognito*
4. open new incognito window `Ctrl+Shift+N` and go to https://bhaskarvk.github.io/colormap/

If it still doesn't work, it would help me to pinpoint the issue:

1. paste content of console log when activating the dropper until the click
2. confrim that you are seeing only black or white also during hover or hover is ok and only after click you receive black/white?

Thanks

P.S.: if somebody on MacOS could confirm anonymous mode thing, it would be great too. Best with same colormap page so I can narrow the problem.

**Comment by sharbel97** [comment]
Hi, 
Chrome Version 80.0.3987.149 (Official Build) (64-bit)
Mac OS Catalina 10.15.3

Still doesn't work (even in incognito). Here is the additional info you asked for: 
<img width="596" alt="Screen Shot 2020-03-28 at 7 37 23 PM" src="https://user-images.githubusercontent.com/38640642/77837162-907f0f80-712b-11ea-96f5-77c8851201bf.png">

I can confirm I'm seeing black/white during hover, and once clicked, it's copying either black/white. If hover is black, it copies black, if hover was white it copies white. But those are the only 2 colors it's showing during hover, some areas on the webpage show white some show black. I haven't seen a pattern/consistency.

**Comment by kepi** [comment]
I still don't have any luck with reproducing the problem. I'll try add some way to acquire more detailed log directly from the extension and let you know.

**Comment by hannahcarroll** [comment]
Sorry for the delay! Here's what I'm seeing on my end. Please let me know if there's other info you need. I'm happy to help dig into it.
![Dropper3](https://user-images.githubusercontent.com/21133688/78379989-d2c7a700-7598-11ea-837f-9de2c1635dae.png)
![Dropper1](https://user-images.githubusercontent.com/21133688/78379994-d4916a80-7598-11ea-950a-1f2ee62e3678.png)
![Dropper2](https://user-images.githubusercontent.com/21133688/78379998-d5c29780-7598-11ea-80df-cf35df1a3a79.png)

**Comment by kepi** [comment]
I think I finally found the problem. It will take me little more time to cleanup and test new version, but I hope fix is coming in couple of days.

@hannahcarroll can you please send what is the value of `window.devicePixelRatio` when typed in Chrome Console?

@naomihyett  is it possible you are using better monitor (with retina) now? Or maybe different Mac then before?

**Comment by hannahcarroll** [comment]
The value I have is 2.5

**Comment by kepi** [comment]
Thanks, thats what I suspected. If you are brave enough :) you can test [new alpha release](/kepi/chromeEyeDropper/releases/download/next/EyeDropper_0.5.4-alpha.crx). Just drag&drop it to `chrome://extensions` page. Its probably good idea to temporary deactivate normal Eye Dropper because alpha one will have same icon.

I hope it will resolve the problem, it would be great to know for sure :)

**Comment by hannahcarroll** [comment]
Installed! It's reacting now, but it's showing white when I hover over colors, and sometimes finding colors when I hover over white. It seems to think my cursor is over a different part of the screen.
![screenshot4](https://user-images.githubusercontent.com/21133688/80164003-75be8000-859d-11ea-8b3c-fdbe90f6a69e.png)
![screenshot1](https://user-images.githubusercontent.com/21133688/80164005-76efad00-859d-11ea-8b2c-264a3aebe10f.png)
![screenshot2](https://user-images.githubusercontent.com/21133688/80164007-77884380-859d-11ea-8852-d966c3d5e377.png)
![screenshot3](https://user-images.githubusercontent.com/21133688/80164009-7820da00-859d-11ea-9e1e-325e94247bf2.png)

**Comment by kepi** [comment]
There goes my hopes :sob: 

Anyway thanks for tests and detailed description. I belive we are on right track. Btw, i forgot to remove one debug tool from alpha release, but it might help me now. When you first clicked pickup color on that page, is it possible that new tab appeared in your browser (url should end with `debug-tab.html`). If so, can you send me screenshot of that tab? You will recognize it immediately, should looks something like this one:

![debugtab](https://user-images.githubusercontent.com/105303/80164662-e7b4ba80-85d9-11ea-8da1-2f63d4b44184.png)

Thanks!

**Comment by hannahcarroll** [comment]
I see it! I was wondering what that was. :)
![screenshot5](https://user-images.githubusercontent.com/21133688/80164914-cafb9100-859f-11ea-9f76-54814be7f628.png)

**Comment by kepi** [comment]
Yeah :) I have to be carefull to not publish this to production version.

Anyway, is it possible you have the page zoomed? Can you try reset zoom to 100 % if so and check if it is working?

**Comment by kepi** [comment]
I believe it would be working without app zoom, but don't worry about it yet. I think I know the way how to go around this, I'll try it first. But it would help if you can give me hint about where to set that default zoom in windows so I can check it myself during development. Thanks again.

**Comment by hannahcarroll** [comment]
For me it's under display settings.
![Picture1](https://user-images.githubusercontent.com/21133688/80165927-42cabb00-85a2-11ea-8a86-dfe49a414846.png)

**Comment by kepi** [comment]
Ok, it took longer then I expected but looks like maybe I got it, at least for windows display problem.

@hannahcarroll would you be so kind and test new  [new alpha1 release](/kepi/chromeEyeDropper/releases/download/v0.5.4-alpha.1/EyeDropper_0.5.4-alpha1.zip)?

It would be great to test on macOS too. Can anybody confirm if it is working or not there? 

btw. I'm attaching only *zip* version as I found that *crx* is no longer supported on many systems and can't be installed there. Just:

1. unpack the zip to some folder
2. go to `chrome://extensions` page
3. enable developer mode
4. click *load unpacked*

Again - I recommend to remove old dev extensions and at least temporarily disable normal Eye Dropper.

**Comment by hannahcarroll** [comment]
That worked!! Here's what I am seeing now. When I click a color, it chooses the right one, and it senses the cursor position on my screen correctly.
![screenshot1](https://user-images.githubusercontent.com/21133688/80978064-2f61f000-8deb-11ea-9f1f-93c0e1b10d91.png)
![screenshot2](https://user-images.githubusercontent.com/21133688/80978071-325ce080-8deb-11ea-8e0b-20318547be91.png)

**Comment by kepi** [comment]
New version (0.5.4) with fix for this bug is already published in Chrome Store and should be auto updated in your browser.

Thanks all for reports and especially @hannahcarroll for help with testing.
