### ISSUE TITLE
Not picking up color from Images

### ISSUE THREAD

**Issue by JDracolyte** [kepi/chromeEyeDropper#142]
Hello! I found that Eyedropper does not work on images, such as from Google or Instagram. I have seen other Eyedropper tools do this, can you fix it?

**Comment by kepi** [comment]
Hello, you mean on downloaded images or directly on website with images? Can you send one URL where it doesn't work for you?

**Comment by JDracolyte** [comment]
Sure: https://www.instagram.com/royale_designs/

**Comment by kepi** [comment]
Hm, it is working without any problem for me. Can you describe where it differs from my experience (see attached screencast) or maybe attach screencast with your experience?

![ed_instagram](https://user-images.githubusercontent.com/105303/78087868-b96d0200-73c2-11ea-9e33-4c0a4ec657da.gif)

Thanks

**Comment by JDracolyte** [comment]
It just shows up black or white when I hover over a pic. I'll uninstall it and see if it works

**Comment by kepi** [comment]
Ah, in that case this is just duplicate of #141

I'll close this issue and continue in previous one. If by any chance you get it working, please let me know.

**Comment by kepi** [comment]
Duplicate of #141
