### ISSUE TITLE
Delete color from pallet 

### ISSUE THREAD

**Issue by JM141989** [kepi/chromeEyeDropper#143]
So i get that i can make pallets and delete them.
but what if i want to only delete one or two colors....

is this even possible if not.... it should!

**Comment by kepi** [comment]
Hey, thanks for feedback. Currently it isn't possible, but it totally make sense.

I'm working on new version currently, maybe I'll be able to squeeze it to next release. No promises.

**Comment by JM141989** [comment]
Awesome thank you for the response!
Awesome little plugin man. :) 👍💯

**Comment by kepi** [comment]
Just found out this is duplicate of #125 

Wasn't able to squeeze it to last release but I'll work on it soon I hope.

**Comment by caleysueee** [comment]
Any updates for being able to delete one or two colors from a palette?

**Comment by caleysueee** [comment]
Nevermind. I was able to figure out how. :)
