### ISSUE TITLE
After removing all color palettes stopped picking colors at all

### ISSUE THREAD

**Issue by smiley-cz** [kepi/chromeEyeDropper#144]
I played with the palettes and removed all of them and suddenly the extension stopped picking any color. It shows all the values in the info-box in the corner of the page but no color gets picked. Not even copied into the clipboard. Changed settings, enabled, disabled right-click. Removed and re-added the extension. Tried in anonymous window. Disabled adblocker etc. Even created a new palette. Using the color picker it works, but using the eye-dropper tool it does not. 🤷‍♂️

**Comment by kepi** [comment]
Thanks for the report and sorry for trouble. To be honest - I don't understand how this can even happen :) When you remove and re-add extension, everything is cleared and there should be no way it doesn't work again.

What operating system are you using and what Chrome version? I suppose extension auto updating is turned on, so latest version should be present.

Fastest way to resolve this would be probably if I prepare extension with logging enabled and you'll try that and send me logs. Would you mind?

**Comment by smiley-cz** [comment]
I am on macOS - latest, Chrome - latest, extension latest. 
I would gladly help with the logs etc. since this EyeDropper is my favorite one (and has been for quite some time)

**Comment by kepi** [comment]
Just uploaded *dev* version to releases page. I'm afraid it would be some hard to investigate problem and we will not get much usefull info in your case but lets try it.

I just put together some information about how to take debug logs. Try it: https://github.com/kepi/chromeEyeDropper/wiki/What-to-do-if-asked-for-logs

Debug tab image should not be needed, but doesn't hurt either :)

Thanks.

**Comment by smiley-cz** [comment]
Hi,
thank you for the dev version. I installed it as described and here are the logs:
(it behaves same as before :( )
![console](https://user-images.githubusercontent.com/1065977/82422986-760a4800-9a83-11ea-894c-07a9a64f1cca.png)
![background](https://user-images.githubusercontent.com/1065977/82422995-786ca200-9a83-11ea-940a-803b6c257c60.png)
[github.com-1589962504046-console.log](https://github.com/kepi/chromeEyeDropper/files/4655520/github.com-1589962504046-console.log)
[iboailniiillkjohliphmjabngfejjdn-1589962520009-background.log](https://github.com/kepi/chromeEyeDropper/files/4655521/iboailniiillkjohliphmjabngfejjdn-1589962520009-background.log)

**Comment by kepi** [comment]
Just uploaded new dev zip to releases. Please try once again and send me new logs and *debug image* too, I was wrong about no need for it :)

It should behave little different now - it should pick white color instead of none but something is definitely wrong, not sure what yet.

**Comment by smiley-cz** [comment]
Indeed it picked up white. One time.
Here are two logs + debug image + screenshots from the extension error page. I tried to open it in normal and anonymous window with all other extensions disabled.

![debug-image-01](https://user-images.githubusercontent.com/1065977/82448315-d4e2b800-9aa9-11ea-9299-b5f5bb242656.png)
[github.com-1589978327621.log](https://github.com/kepi/chromeEyeDropper/files/4656943/github.com-1589978327621.log)
[ngbbmeiflplbifmkobpkpofejjdbkhma-1589978406102.log](https://github.com/kepi/chromeEyeDropper/files/4656944/ngbbmeiflplbifmkobpkpofejjdbkhma-1589978406102.log)
[ngbbmeiflplbifmkobpkpofejjdbkhma-1589978898405-anonymous.log](https://github.com/kepi/chromeEyeDropper/files/4656945/ngbbmeiflplbifmkobpkpofejjdbkhma-1589978898405-anonymous.log)
[www.checklist.design-1589978908463-anonymous.log](https://github.com/kepi/chromeEyeDropper/files/4656946/www.checklist.design-1589978908463-anonymous.log)
![debug-image-02-anonymous](https://user-images.githubusercontent.com/1065977/82448324-dca25c80-9aa9-11ea-974c-2d619bf5ea36.png)


![01](https://user-images.githubusercontent.com/1065977/82448285-cc8a7d00-9aa9-11ea-8b0e-75369e697413.png)
![02](https://user-images.githubusercontent.com/1065977/82448289-cdbbaa00-9aa9-11ea-9f44-08b1813b9f5c.png)
![03](https://user-images.githubusercontent.com/1065977/82448291-ce544080-9aa9-11ea-989c-3c09461418dc.png)
![04](https://user-images.githubusercontent.com/1065977/82448294-ceecd700-9aa9-11ea-82e0-6dcdb967edb9.png)

**Comment by kepi** [comment]
I'll try to look into later today. To be sure - I know you already confirmed this in first post - when you are moving the mouse on screen, it is showing correct colors in small corner box? Only when clicked it pick only white/none? I'm ensuring because its really weird - code for getting color when click or moved is almost the same, it almost look like some system error.

I once again updated dev zip and if you could try once again, it would help me make more sense about this. Its enough to try it in normal mode (other extension disabled is always great, thanks for that) and just attach the logs from both consoles, no need for screenshot and no need for debug image.

**Comment by smiley-cz** [comment]
No rush :) But it is odd indeed. I'll try on another mac later.

Yes - the color gets shown in the bottom right corner and it changes according to the one I hover over. When clicked nothing gets picked. (White in the dev version gets picked and even copied into the clipboard) I even checked for set shortcuts if they don't interfere (weird longshot - I know...) and disabled them. Still the same.
From what I vaguely remember this started to happen by the time I deleted the picked palettes. But oddly the colors and palettes get created when using the "color picker".

[ojjclomemcjiobdjpklaheecljeoiimk-1589982685813.log](https://github.com/kepi/chromeEyeDropper/files/4657271/ojjclomemcjiobdjpklaheecljeoiimk-1589982685813.log)

[github.com-1589982670771.log](https://github.com/kepi/chromeEyeDropper/files/4657270/github.com-1589982670771.log)

**Comment by kepi** [comment]
Debug image is as it should be. It looks weird probably when so long but it simply displays already captured part of page. You started ED while scrolled in this long issue, thats why there is that long white space at start - part of page were you not scrolled to.

Anyway I uploaded new dev version. It should fix one part of log file which wasn't complete, but more importantly :) it maybe fix the issue for you.

Let me know if it helps and please upload the *pickup log* (bg not needed) even if it works, I want to double check something.

**Comment by smiley-cz** [comment]
Works wonderfully! Thank you!

Here is the log.
[github.com-1590053291036.log](https://github.com/kepi/chromeEyeDropper/files/4661626/github.com-1590053291036.log)

I also checked on another Mac using the store release and it worked there (under my account etc.) Windows version worked fine after installing the store version. So it looks as some sort of local problem :(
Anyhow - now in the dev version picking colors works. I would gladly help to test any other versions if needed.

**Comment by kepi** [comment]
Just uploaded new version with fix to Chrome Store and now is pending review. Production version will be auto updated as soon as they approve it.

Díky za nahlášení a za pomoc.
