### ISSUE TITLE
Offline mode request

### ISSUE THREAD

**Issue by alienjedi** [kepi/chromeEyeDropper#145]
I use this extension when I am building websites. But I often work offline and so can't use it. Found this issue on windows. Don't know for other platforms.
Here requesting offline working mode!!

**Comment by kepi** [comment]
Hello, I'm really not aware of any reason why Eye Dropper shouldn't work offline. Only part which requires some connection is storing picked colors, but this should be done by Chrome behind the scene and is working offline without any problem.

Isn't the problem you are developing your websites on `file://...` URLs? If that is the case, let me know. It wasn't possible in past for extensions to access local file system but there may be the way now so I can investigate it.

Anyway, if thats the case, unsolicited advice from another developer :) - use local webserver to build websites. You can setup apache/nginx and access your sites on vhosts like **mysite.localhost**. It brings the benefit of more real environment.

**Comment by alienjedi** [comment]
I actually found this issue in Windows OS but I'm now using Linux. 
And I was developing angular apps so I basically had a server running, I wasn't saving colors from `file://....` websites. But, I didn't save colors though. So I figure maybe that might be what I did wrong.
If you say it is possible, then I'll just let this issue rest and close it.
Closing.
