### ISSUE TITLE
Quick value copier

### ISSUE THREAD

**Issue by VioletGreyAprilAndMay** [kepi/chromeEyeDropper#146]
On the eye-dropper, it would be great to copy by clicking on one of the values on the right (e.g. the hex value, the hsl value) so that I can paste it in another app (e.g. another colour selector).

**Comment by kepi** [comment]
Good idea, thanks! Not sure when, but I would like to do this.

**Comment by VioletGreyAprilAndMay** [comment]
Cool, thanks! I love the app.

**Comment by kepi** [comment]
Took a little time :/ but it is finally implemented and will be available in nexte version.

You are welcome to help me beta-test it in https://github.com/kepi/chromeEyeDropper/issues/256
