### ISSUE TITLE
Really mad that the keyboard shortcut isn't working. 

### ISSUE THREAD

**Issue by Ani-Xan** [kepi/chromeEyeDropper#152]
The Alt+P Keyboard shortcut to use the Eye Dropper isn't working. I've tried changing it (shortcuts), disabling other extensions, quitting chrome, and changing other program shortcuts. It still isn't working. Someone please fix this. (Alt+Shift+P still works, it starts the extension.)

**Comment by kepi** [comment]
Thanks for report. To be able to help, I need at least what operating system are you using and what version.

`Alt+P` might conflict with some system shortcut, can you try to set it to `Alt+Shift+P` (whiched worked for you for starting extension so we are sure this isn't problem? You mentioned changinge other program shortcuts - I'm not sure if you meant shorcuts of other extensions or of eye dropper.

Can you please confirm this is not working when all other extensions are disabled? `Alt+P` might colide with some system shortcut too, s

**Comment by Ani-Xan** [comment]
I am on Windows 10, Chrome Version 86.0.4240.75 (Official Build) (64-bit). I have tried disabling all other extensions, I have looked through my shortcuts multiple times, and Alt + P still doesn't work. Hope this will help, @kepi

**Comment by kepi** [comment]
To be clear, if you use `Alt+P`, it should start pickup from web but you still have to move the mouse. When you use the shortcut and  just move the mouse, it isn't doing anything or is it working? Unfortunately it isn't possible to pick color from cursor position just with shortcut currently - limitation of Chrome's API.

If it doesn't work, I'll need to get some debug logs from you (I'll describe how to get them) as it is working on W10 computer where I tried to reproduce the problem.

**Comment by Ani-Xan** [comment]
@kepi →→→ Hey, I just tried the shortcut again and it seems to work. I think some other software I have installed was interfering, or just the Windows OS itself. 
`Alt + P` now works, as well as `Alt + Shift + P` (and `U`)
Earlier, when I used the shortcut, the little color box didn't appear, even after moving my mouse. 
Thanks for trying to help!

**Comment by kepi** [comment]
Great, I'm glad its working for you. Cheers.
