### ISSUE TITLE
Suggestion: ability to remove colors from palette

### ISSUE THREAD

**Issue by DBSeamz** [kepi/chromeEyeDropper#153]
So, I've been using this extension combined with Planet Minecraft's skin editor to make Minecraft skins based on characters from an animated TV show I like. So far it's been working great--I find a screenshot of the character in the outfit I want to make into a skin, and sample each color in the outfit to make a palette I can then refer to when typing color hexcodes into the skin editor's paint tool. However, if I accidentally misclick and pick a background color I don't need, I would like the ability to remove that color from the palette without wiping the entire palette and starting over.

**Comment by DBSeamz** [comment]
This is a Wishlist (Whishlist?) item by the way--I don't see a way to attach labels?

**Comment by kepi** [comment]
Thanks for your suggestion. This is defenitely on top of my list just not sure when I'll find some time to work on it.

as for labels - only repo managers can do this, don't worry about them.
