### ISSUE TITLE
Unable to pick colour on local file (even though access has been granted within Chrome)?

### ISSUE THREAD

**Issue by rc-nbsimmons** [kepi/chromeEyeDropper#154]
My understanding is that, by default, Chrome prevents extensions from accessing local files etc.

A Chrome update brought the ability to allow file access (to URLs like file://) for extensions. I've enabled this but it seems the extension still doesn't acknowledge it (https://tinyurl.com/y698y8cc).

Is there anyway to get round this? I believe this is the most accurate extension for an eye dropper and don't want to be forced to use another extension.

**Comment by kepi** [comment]
Thanks for report. I have to check current possibilities, as I hardcoded that it should not work for `file://` as it wasn't possible before.

I can't promise anything as I'm currently without any free time but if it is possible, it should be super easy to implement.

**Comment by kepi** [comment]
Ok, looks like it is working. Just published new version (0.5.7).

Thanks again for reporting.
