### ISSUE TITLE
can't copy color codes from palette

### ISSUE THREAD

**Issue by vonoy** [kepi/chromeEyeDropper#156]
I used to be able to drag my cursor over any single color code to copy via cmd+c cmd+v to elsewhere. I saw another github ticket that is asking for the ability to copy by just clicking on a code, which would be amazing, but for now I'd be happy with just being able to select text like I used to be able to. 

I've found this extension to be extremely useful, but it's far less useful now that I have to manually write down every color code to then type it into whatever I'm working on. I noticed this change several months ago, but am only reporting it now.

**Comment by kepi** [comment]
Thanks for the report, I can confirm it isn't working on macOS currently and it definitelly should. I'm guessing you are using macOS from `cmd+c` part.

I'm not yet sure how to workaround the issue. Chrome seems to behave differently on macOS then on other platforms. There is experimental clipboard API which should work but from couple tests I tried just now I'm not sure if it is the right way.

**Comment by kepi** [comment]
I fixed this about year ago and probably didn't include the fix in release by mistake. Should work since 0.5.10 release.
