### ISSUE TITLE
Constantly opens a Chrome window when starting Chrome

### ISSUE THREAD

**Issue by ARNO-UK** [kepi/chromeEyeDropper#161]
It gets annoying to always having a window opening when first opening Chrome
Can this be dealt with?

**Comment by kepi** [comment]
It definitely shouldn't happen. There was once similar issue but we didn't find any cause. Can you please try to uninstall extension and install it again? It will delete your color history - if that is the problem, let me know and I'll try to think about something else.

**Comment by kepi** [comment]
Closing as there is no response. If you hit it again, please reopen or create new issue.
