### ISSUE TITLE
Shortcut Alt+P stopped working

### ISSUE THREAD

**Issue by EranOsishkin** [kepi/chromeEyeDropper#162]
The Alt+P shortcut used to work like a charm and in the past several days it isn't working for me.
Even tried removing and re-adding it in the Chrome settings but still doesn't work.

**Comment by kepi** [comment]
Thanks for report. Can you please send me what Chrome version are you using and what Operating System?

Btw. can you open `chrome://extensions/shortcuts` page in your Chrome and check if you have `Alt+P` assigned there?

**Comment by EranOsishkin** [comment]
I updated Chrome and it works again.
Thanks!
