### ISSUE TITLE
"Pick Color" Feature not working

### ISSUE THREAD

**Issue by Wintrom21** [kepi/chromeEyeDropper#167]
When I installed the eyedropper extension and click on the "pick color from webpage" button, the pointer does not work. I tried disabling other extensions that could be blocking the eyedropper from working, but still nothing. The button simply grays out but nothing happens.

**Comment by kepi** [comment]
Hello, really sorry for this. I fixed this about hour ago (see #166) but it took some time before updated version is published and even more time then your browser auto update it.

If you want to speed things up, you can go to `chrome://extensions/` page, click on the "Developer mode" in top right corner and then click on "Update" on top left corner. This should update Eye Dropper to latest version 0.5.8 and fix this problem. You can then disable "Developer mode".

**Comment by Wintrom21** [comment]
Oh ok, thanks for getting back to me! I'll go ahead and update it and see how it goes. Thank you for your great work! 🙂

**Comment by kepi** [comment]
I believe this is fixed and closing the issue hoping everybody is now auto updated to latest version.
