### ISSUE TITLE
Impossible to pick these days

### ISSUE THREAD

**Issue by Eloyaz** [kepi/chromeEyeDropper#169]
The extension is out for me since a few days. Didn't change anything in my features. Simply using the color picker for my graffic creations. It was SO helpful, i am lost without it.
Others in this situation ?

**Comment by kepi** [comment]
Thanks for report @Eloyaz  What operating system do you use? Your chrome version may be usefull too.

**Comment by kepi** [comment]
I hope you got it working and only forgot to update back.
