### ISSUE TITLE
Publish to Firefox add-ons website

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [kepi/chromeEyeDropper#175]
It would be nice if your extension available at Firefox add-ons website (along with #174)

**Comment by kepi** [comment]
I'm thinking about supporting more browsers, Firefox would be first probably. But I still need to finish some long standing issues first and can't promise any reasonable ETA.

**Comment by Sundew-plays** [comment]
ill help test

**Comment by kepi** [comment]
Eye Dropper is finally available for firefox: https://addons.mozilla.org/en-US/firefox/addon/eye_dropper/

I'll be glad if you give it a try and let me know if it works for you or not. Even "everything OK" would be great so I know that somebody else tried it but me. If something doesn't work as it should, please open new issue.

And if it works :) I'll be definitely glad for honest review in addon store.

**Comment by Sundew-plays** [comment]
Yoo thanks I'll test it also sorry GitHub never gives me notifications.
