### ISSUE TITLE
Hexcode is stuck on my website's page and I can't get rid of it

### ISSUE THREAD

**Issue by anashm15** [kepi/chromeEyeDropper#181]
The color dropper hexcode is stuck on my Wix website page and I'm not sure how to get rid of it.  This is the first time this has happened, but any advice on how to get rid of this would be greatly appreciated.

Thanks!
![Website - Color Dropper glitch](https://user-images.githubusercontent.com/87043809/124670481-0bcc8680-de82-11eb-9e2a-d4f83785f9fd.png)

**Comment by kepi** [comment]
@anashm15 are you sure this hex code is from this extension? It looks totally different than anything I'm using :)

**Comment by kepi** [comment]
closing as there is no response
