### ISSUE TITLE
Alt + P not working

### ISSUE THREAD

**Issue by teroxrr** [kepi/chromeEyeDropper#182]
Hello,

For some reason the `Alt + P` shortcut doesn't seem to be working for me.
I'm using a Macbook Pro running Mojave 10.14, Chrome v91.

I tried changing the shortcut in Chrome, using different letters and adding other keys like `Shift + Alt + P`.
Nothing seems to work. 
I hope you can help me. 

Thanks!

**Comment by deniboi123** [comment]
Working fine for me using Brave Version 1.27.111 (Chromium 92.0.4515.131).

**Comment by kepi** [comment]
@teroxrr sorry for long delay. Did you manage to get it working or is this still an issue?

**Comment by kepi** [comment]
no reply for long time, closing
