### ISSUE TITLE
One less mouse click?

### ISSUE THREAD

**Issue by VTGroupGitHub** [kepi/chromeEyeDropper#184]
Very nice plugin.  A feature request if possible:

My ideal usage would be to click the button on the Chrome toolbar, and then immediately pick the color on the page.  Having to hit "Pick color from webpage" in the middle is just an extra click for me.

Is there a way, or can you add a Setting, so that we can select in just two clicks?

**Comment by kepi** [comment]
Thanks for your idea. This has been planned for quite a time but so far there were different priorities. I'm closing this in favor of the original issue #18

Feel free to subscribe to notifications in #18 to be notified if/when it happens. No promises, I'm really not sure myself if it is close or not.
