### ISSUE TITLE
Can't drag Eye dropper colour selector to different position.

### ISSUE THREAD

**Issue by smithy49** [kepi/chromeEyeDropper#186]
I was trying out the Eye Dropper but unfortunately the window positions itself in the bottom right of the web page and in my case was hidden by an up arrow. Please make the window **relocatable**.

![eyedropper](https://user-images.githubusercontent.com/6471037/131219044-56899524-764b-4c51-b394-8f6c89718ba8.JPG)

**Comment by kepi** [comment]
Thanks for your report, you are right, it should be relocatable. It should at least be top-most layer so it always hide anything under, but still movable box would be better.

Can you please send me address of the page where this happens so I can test it more easily?

**Comment by smithy49** [comment]
Scroll down on the page until the green up arrow is visible.

Link:https://newsbook.com.mt/en/
Thanks
    On Saturday, 28 August 2021, 14:17:45 BST, Kepi ***@***.***> wrote:  
 
 


Thanks for your report, you are right, it should be relocatable. It should at least be top-most layer so it always hide anything under, but still movable box would be better.

Can you please send me address of the page where this happens so I can test it more easily?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kepi** [comment]
This was fixed couple days ago in version 0.5.10. It still isn't relocatable, but at least it is visible over the arrow.

I'm planning on doing some color box redesign in the future with positioning in mind.
