### ISSUE TITLE
Would it be possible to add a function of updating frames per second?

### ISSUE THREAD

**Issue by IgoriGpon** [kepi/chromeEyeDropper#190]
Would it be possible to add a function of updating frames per second?

Does the program refresh the screen 30 times a second to recognize colors from a video being played? (The reason I want this function is that I want to assign to a game that the player recognizing a color will take damage, this game will work on youtube video playback.)

**Comment by kepi** [comment]
Hello, this wouldn't be possible with current recognition core. It simply analyzes screenshots, and taking screenshot took some time which is close to one second... so can't work with such speed even remotely.
