### ISSUE TITLE
Color picker not picking color.

### ISSUE THREAD

**Issue by Joan-Maina** [kepi/chromeEyeDropper#203]
I am using https://dribbble.com/ to get some inspiration and the color picker does not pick a color. In fact, the cursor remains as the default instead of changing to the one used when picking a color.

**Comment by thinklikebeast** [comment]
just choose the color from the image. i think this color ain't work in dribble.com

**Comment by kepi** [comment]
Thanks for report. I can see this is happening on image detail which is implemented in some modal window.
