### ISSUE TITLE
The crosshair cursor not working

### ISSUE THREAD

**Issue by RevisedJDUDE2** [kepi/chromeEyeDropper#204]
The crosshair cursor not working:
I Change pointer to crosshair and it didn't work

**Comment by kepi** [comment]
Thanks for the report. What operating system are you using?

**Comment by kepi** [comment]
I'm not able to reproduce it so far. Is it possible, that you didn't save the settings?

I'm so used too auto saving of preferences in most apps that I forgot it myself at first.

**Comment by kepi** [comment]
no reply for long time, clossing
