### ISSUE TITLE
Sending to eyedropper.test instead of eyedropper.org

### ISSUE THREAD

**Issue by dlopezmx** [kepi/chromeEyeDropper#205]
Hi! While trying to access to a help doc from the chrome extension it is sending me to "https://eyedropper.test/help/file-urls", which gives an error. If I just change ".test" for ".org" it sends me to the correct URL. 
This is where I accessed that URL:
![image](https://user-images.githubusercontent.com/100050609/165332757-5037859d-0d0b-4b18-a26c-40c2dd08654a.png)
Have a great day

**Comment by kepi** [comment]
Thanks for report, fixed in next version. I'll try to release it soon.
