### ISSUE TITLE
Trash only 1 color at a time

### ISSUE THREAD

**Issue by blainelight** [kepi/chromeEyeDropper#207]
Hi Team, would love if I can trash 1 color at a time instead of the whole pallet. 

Workaround -- I could download the csv then re-upload it once I removed colors, but I don't think we can re-upload either. Thanks!

**Comment by kepi** [comment]
You are correct, both things are impossible at the moment. And both would be great to have.

**Comment by kepi** [comment]
deleting color will be possible with next version, which should arrive next week. Sorry it took so long

fixed in 0d29ff8

**Comment by blainelight** [comment]
Great! Thanks 😊

Blaine
blainelight.me

**Comment by kepi** [comment]
forgot to close this, this has already been ready for couple months now.
