### ISSUE TITLE
Not working on any pages/thinks all pages are "special pages"

### ISSUE THREAD

**Issue by emcdaniel99** [kepi/chromeEyeDropper#215]
### Describe the bug

Exact error message is: 

"Whoops. Can't pick from this page
Chrome doesn't allow extensions to play with special Chrome pages like this one.
chrome://..."

But I get this message on every single normal webpage page I visit (with an https://), including many pages it previously worked on as well as this page. I tried disabling and reenabling the extension as well as restarting Chrome, and as far as I know Chrome is fully up to date (I'm on Version 102.0.5005.61 (Official Build) (x86_64)). 

### Expected Behavior

I expected to be able to:
1. Open the extension 
2. Click on the eye dropper color picker button
3. Select colors on general webpages like normal

### Steps To Reproduce

1. My browser has been on page https://github.com/kepi/chromeEyeDropper/issues/ (and every other webpage I visit)
2. I clicked on Eye Dropper icon and Eye Droppers window appeared without a problem
3. Where the "Pick color from web page" button typically is there is a yellow error message box that says:
> "Whoops. Can't pick from this page
> Chrome doesn't allow extensions to play with special Chrome pages like this one.
> chrome://..."
4. I tried restarting Chrome.
5. I tried disabling and reenabling the extension
6. I tried updating Chrome.
7. Nothing fixed it.

### Screenshots

![Screen Shot 2022-05-31 at 9 00 50 AM](https://user-images.githubusercontent.com/106604296/171193492-8f48bf38-4187-4e79-bd27-e638b3a2f342.png)

### Operating system

macOS

### Browser version

Version 102.0.5005.61 (Official Build) (x86_64)

**Comment by ShaneHicks** [comment]
Can confirm this is an issue on both Windows and Mac devices. v0.5.11 (Chrome 102.0.5005.63 (Official Build) (64-bit))

**Comment by kepi** [comment]
This should be fixed in release 0.5.12 which should be available as soon as it goes through validations (not sure how fast it will be, might take minutes or hours).

@emcdaniel99 @ShaneHicks please let me know if it is fixed.

Btw. as workaround (and if my fix is correct). You should be able to pick colors without problem if you don't have active Chrome Web Store page or extensions page in any current tab (in any opened Chrome window). Or simply by having only one Chrome window opened.

**Comment by ShaneHicks** [comment]
Yes, this issue is fixed automatically.

**Comment by emcdaniel99** [comment]
Yes, I have not had any issues with this before.

Thank you,

[signature_53030031]

Elizabeth McDaniel
Digital Marketing Coordinator


From: Kepi ***@***.***>
Date: Tuesday, May 31, 2022 at 10:28 AM
To: kepi/chromeEyeDropper ***@***.***>
Cc: Elizabeth McDaniel ***@***.***>, Author ***@***.***>
Subject: Re: [kepi/chromeEyeDropper] Not working on any pages/thinks all pages are "special pages" (Issue #215)
Moody ITS Alert: This email is from an external source. Please exercise caution when opening attachments, clicking on links, or replying to the sender.

Thanks for report. I'm really not sure how this can happen. It is fine on Linux, so there has to be some os specific quirk. I suppose this is after last update and had been working well for you before?

I'll try to fix it this evening, sorry for inconvenience.
