### ISSUE TITLE
Has completely stopped working on all pages

### ISSUE THREAD

**Issue by sophiamx1** [kepi/chromeEyeDropper#216]
### Describe the bug

Every time I try to use the extension to pick a colour from a webpage I get the following error message:
Chrome doesn't allow extensions to play with special Chrome pages like this one.
chrome://...

I can still see and copy all my saved colours. I have tested a number of sites that have worked with the extension in the past, and it still has the same error message. I removed and reinstalled it and it still has the same error. I tried to let the extension full site access but I am unable to.

### Screenshots

<img width="540" alt="Screen Shot 2022-06-01 at 9 23 52 am" src="https://user-images.githubusercontent.com/102008034/171299594-577cd8e3-f448-4768-8ddd-bc4953fb87de.png">

<img width="639" alt="Screen Shot 2022-06-01 at 9 21 16 am" src="https://user-images.githubusercontent.com/102008034/171299372-594c4121-90d2-4531-9b1c-0d61809a32b4.png">

**Comment by steph20595** [comment]
Having Same issue

**Comment by kepi** [comment]
HI @sophiamx1 and @steph20595 can you please check if you have latest version (0.5.12) installed? You can see that i.e. when clicking on question mark icon located at bottom of the popup.

If you are on 0.5.11 (which introduced this bug), you can update by:

1. go to [chrome://extensions/](chrome://extensions/) page
2. activate **Developer mode** in top right corner
3. click on **update** button which will appear on left side of screen
4. you can deactivate **Developer mode** after this

Workaround for this issue (fixed couple hours ago in #215) on 0.5.11 is either of:

1. having only one Chrome window
2.  don't have open Chrome Web Store or any chrome:/// page in active tab in any window

If updating doesn't help you or you are already on 0.5.12 and still not working, please let me know.

**Comment by sophiamx1** [comment]
Yep, 0.05.12 works great! Thank you!
