### ISSUE TITLE
Doesn't save new colors

### ISSUE THREAD

**Issue by SamCalliberYT** [kepi/chromeEyeDropper#217]
### Describe the bug

Whenever I pick a new color, it doesn't save. I've attempted on two devices, with different amounts of colors already saved before the bug started happening. On both, the colors just wouldn't save. Whenever I turn off the device or put it to sleep, any colors I picked that day just disappear.

### Expected Behavior

The colors to stay, I guess?

### Steps To Reproduce

I select a color, and I do what I need with that color.
I put the device to sleep
When I turn it back on in the morning, the color is gone.

### Operating system

Windows

**Comment by kepi** [comment]
Thanks for reporting this.

To help me debug this:

1. Do you have synchronization enabled in Chrome?
  2. If yes, how many devices are you synchronizing?
  3. If there is more devices, what are their state when you putting the device to sleep
1. How many (roughly) colors have you stored?
4. How many different palettes?
5. Not sure if this would be needed, but if so: Are you willing to help me with debugging? If yes - do you know your way around i.e. Web Developer Tools in Chrome or not (so I know how much technical I should be).

My first guess would be, that there is something wrong with Google Chrome synchronization for your device. I didn't touch color storing part for long time and I don't think that error would be in color storing, but can't rule it out (yet).

**Comment by SamCalliberYT** [comment]
Well,
1. One of the devices was an entirely separate account, and I do have synchronization on. The other device when put to sleep shut down entirely, but I no longer use it.
2. I have roughly 144 colors stored (That might be the exact issue but I think I had less on my other device).
3. I only have one palette.
4. And I'd love to help with the debugging, but I'm not familiar with Web Developer Tools.
