### ISSUE TITLE
Color code not copied

### ISSUE THREAD

**Issue by rkiriadre** [kepi/chromeEyeDropper#220]
### Describe the bug

Hi! Since 1 or 2 weeks ago, I haven't been able to automatically copy the hex code when clicking the square color. Can you pls help me?

### Expected Behavior

Click on square color to copy hex code.

### Operating system

macOS

### Browser version

Chrome Version 102.0.5005.61

**Comment by kepi** [comment]
Thanks for your report! Problem is fixed in latest version (0.5.13) which will be published as soon as it is verified on Chrome Web Store (usually couple hours).

**Comment by rkiriadre** [comment]
Thank you so much! I can confirm you it works!
