### ISSUE TITLE
Losing Folders

### ISSUE THREAD

**Issue by robertbrill** [kepi/chromeEyeDropper#221]
### Describe the bug

Twice I created folders, and saved colors to them. Then, I will close down Chrome, and I lose the folders.

### Expected Behavior

The folders should remain on my account indefinitely.

### Steps To Reproduce

I create folders
I either shut down Chrome, or turn off computer
Folders are no longer there
Done this twice

### Screenshots

<img width="539" alt="Screen Shot 2022-07-11 at 5 56 23 PM" src="https://user-images.githubusercontent.com/67603968/178385173-9456a441-d69e-4904-ae4e-55da6b1e9505.png">

### Operating system

macOS

### Browser version

Version 103.0.5060.114 (Official Build) (x86_64)

### Anything else?

No. Otherwise, love the tool. Thanks.

**Comment by kepi** [comment]
Thanks for reporting the issue. Couple questions:

1. Default palette works fine? If you pick new color, it stays there after quitting Chrome or shutting down PC?
2. Do you have Chrome syncing turn on? (logged into google account to synchronize Chrome)
3. Do you have another computer with same account?

**Comment by robertbrill** [comment]
Hi Kepi,

Default works fine. I don’t know if new colors are staying inside default after restarting Chrome or shutting down the PC.

Yes, I have Chrome Sync on.

I have Chrome logged into 2 other computers.


From: Kepi ***@***.***>
Reply-To: kepi/chromeEyeDropper ***@***.***>
Date: Thursday, July 14, 2022 at 3:04 AM
To: kepi/chromeEyeDropper ***@***.***>
Cc: robertbrill ***@***.***>, Author ***@***.***>
Subject: Re: [kepi/chromeEyeDropper] Losing Folders (Issue #221)


Thanks for reporting the issue. Couple questions:

  1.  Default palette works fine? If you pick new color, it stays there after quitting Chrome or shutting down PC?
  2.  Do you have Chrome syncing turn on? (logged into google account to synchronize Chrome)
  3.  Do you have another computer with same account?

**Comment by kepi** [comment]
I'm terribly sorry it took me so long to reply, I had to have missed the notification somehow :(

If this is still an issue for you, can you please check, that you have unlocked plus on all three systems before trying to create new palette?

**Comment by kepi** [comment]
no update, so I'm closing this. As palettes system has been completely rewritten in next version, this will be hopefully fixed even if it wasn't yet.
