### ISSUE TITLE
Doesn't work for me and documentation doesn't explain how to use it

### ISSUE THREAD

**Issue by rustyweaver** [kepi/chromeEyeDropper#222]
### Is your feature request related to a problem?

It doesn't let me pick any color and when I read the documentation it doesn't explain
how precisely to use it, or visually demonstrate the use of it.

Here's what I did:
  Open the extension
  Click the button "Pick color from web page"

What happens:
  The extension popup disappears.  Nothing else happens.

What I expected would happen:
  It would let me move the cursor over different element of the web page and automatically update the rgb code.

I looked through all the documentation.  Tried the keyboard shortcuts (but they aren't documented
for mac keyboards).  Nothing happens.  Do I need to enable popups?  I didn't see any rgb numbers anywhere.
Probably something simple, but I couldn't find any usage instructions.

### Describe the solution you'd like

A video showing what the screen looks like as you use the tool.

**Comment by kepi** [comment]
Thanks for taking time to report this problem. It should work exactly as you are expecting, this is also the reason I didn't spend time with documentation yet, as it is (should be) kind of intuitive.

Just to be sure, can you please confirm, that you are using recent version of Chrome? If you can paste exact version, it would be great.

Also, just to be sure, on what page are you trying to use it?

And last question, at least for now, did you try to restart Chrome after installing the extension? It shouldn't be necessary but it also should work for you without any problem so I'm trying to find out what is the issue.
