### ISSUE TITLE
Pick from Webpage broken.

### ISSUE THREAD

**Issue by nerd0ne** [kepi/chromeEyeDropper#223]
### Describe the bug

When I click the pick from the webpage, it doesn't work and nothing happens

### Expected Behavior

I clicked the pick from webpage and I wanted it to do it's job.

### Steps To Reproduce

1.I was on the normal google search on the images tab.
2.I clicked the pick from

### Operating system

Windows

### Browser version

90, Opera

**Comment by amiraelbehiri** [comment]
Hi, I am also experiencing this - I tried to refresh and it didn't resolve the issue and tried on different web pages. It just shows a black square.

Google Chrome Version 110.0.5481.177 (Official Build) (arm64) on a MacBook
