### ISSUE TITLE
Removing Colours

### ISSUE THREAD

**Issue by Panimal53** [kepi/chromeEyeDropper#224]
### Is your feature request related to a problem?

When I want to remove some accidently chosen colours, I have to delete the whole thing
e.g.

RED   BLUE   GREEN   PINK

If I wanted to remove BLUE, I would have to delete all

### Describe the solution you'd like

I would like an option to delete singular colours

### Describe alternatives you've considered

none

### Anything else?

nope

**Comment by kepi** [comment]
Removing colors will be possible in the next version, which should be alive at the start of next week.

**Comment by kepi** [comment]
forgot to close this, this is already available
