### ISSUE TITLE
Clicking on colored square does not copy values to clipboard

### ISSUE THREAD

**Issue by smithy49** [kepi/chromeEyeDropper#227]
### Describe the bug

Although Pick color from webpage works and the values are captured, the click on square does **not** work.

### Expected Behavior

I expected the color values to be copied to clipboard when clicking on colored square.

### Steps To Reproduce

My browser has been on page https://eyedropper.org/
I clicked on Eye Dropper icon and Eye Droppers window appeared without a problem
I clicked on Pick color from web page button
The small window appeared in bottom right of webpage
Clicked on colored square but values not copied to clipboard

### Operating system

Windows

### Browser version

Chrome: 106.0.5249.119

**Comment by kepi** [comment]
Thanks for detailed report. Can you please clarify, which colored square are you refering to? There are little too many of them :)

From your description it looks like to me that you might be refering to colored square in "small window" you are mentioning in step 4? If so, this one is not supposed to be clicable, it is just preview of color you are hovering over with your cursor. But you shouldn't be able to click on that - so I'm probably getting it wrong.

Other possibility, which should definitely work, is clicking on small color square in color history which is displayed when you click on Eye Dropper icon. If this is the case, please check Eye Dropper settings, if copying to clipboard is enabled (it should be by default if I remember correctly).

**Comment by smithy49** [comment]
Hi kepi,
Thanks for replying.
I was referring to the square in color history.
It is now working after enabling the option in settings as you suggested.
Thank you for a great tool.

**Comment by kepi** [comment]
Great, thanks for update!
