### ISSUE TITLE
Delete a color from the palette

### ISSUE THREAD

**Issue by dramaswamyy** [kepi/chromeEyeDropper#229]
### Describe the solution you'd like

It would be great to be able to remove a color from a color palette if you "eye drop" the wrong color. If this feature is already in place, it would be ideal to have some explanation on the UI end on how to remove a color from a palette.

**Comment by kepi** [comment]
Removing colors will be possible in the next version, which should be alive at the start of next week.

**Comment by kepi** [comment]
I forgot to close this, as this is already available for couple months.
