### ISSUE TITLE
Pin to page

### ISSUE THREAD

**Issue by rhagerty** [kepi/chromeEyeDropper#231]
### Is your feature request related to a problem?

I'd love to be able to pin this to the corner of my page so it stays open. I use it often!

### Describe the solution you'd like

I'd love to be able to pin this to the corner of my page so it stays open.

**Comment by kepi** [comment]
Hey @rhagerty , thanks for your idea.

Can you please try to describe your ideal process little more? I'm not sure if you'd like to pick more colors at once, or just having easier access to pick button? Or having easier access to color history?

**Comment by kepi** [comment]
I'm closing this as I don't have enough info about your idea. There is still issue to be able to pick more colors at once, which should help you in some way (see #26 ).

If you find time later, feel free to reopen this.
