### ISSUE TITLE
Taking black color as default not changing

### ISSUE THREAD

**Issue by Abhisek753** [kepi/chromeEyeDropper#237]
### Describe the bug

Taking black color as default not changing

### Operating system

Windows

**Comment by kepi** [comment]
Thanks for your report. It would be great if you could provide more details, as I can't help you with as little information.

Is this happening on new installation or had been Eye Dropper working for you before and stopped? Did you try to restart browser after installation? What page are you trying it on? Please describe as much details as you can.

**Comment by kepi** [comment]
Sorry but I can't help witthout more details, closing.
