### ISSUE TITLE
Organizing colors in palettes

### ISSUE THREAD

**Issue by MLO-514** [kepi/chromeEyeDropper#241]
### Is your feature request related to a problem?

1. Adding colors to palettes places them at the end. Not possible to reorder a color closer to others.
2. If you mistakenly add a color to the (wrong) palette, you cannot erase that one color.

### Describe the solution you'd like

1. A drag option to reorder colors.
2. A left-click option to delete a color. Alternatively, a drag option to move color into a "trash" icon to delete it.

### Anything else?

Thanks, love the app!

**Comment by kepi** [comment]
Removing colors will be possible in the next version, which should be alive at the start of next week.

**Comment by kepi** [comment]
Drag option to reorder colors is available in next version (our you can try it now in beta #256).
