### ISSUE TITLE
Eye Dropper Not Working on Website Anymore

### ISSUE THREAD

**Issue by RichyPlays112** [kepi/chromeEyeDropper#244]
### Describe the bug

I Was Using Eye Dropper on the MCD Fandom and The Website had a bunch of errors and eye dropper only was picking white.

### Operating system

None

**Comment by kepi** [comment]
Can you send me direct link to the site?

Is the white picking problem only on that site or on all sites?

**Comment by RichyPlays112** [comment]
only that site, https://minecraft.fandom.com/wiki/Minecraft_Dungeons:Weapon#Melee_weapons
its fixed now, i think it was just a bug on the site

**Comment by kepi** [comment]
Great, thanks for letting me know.
