### ISSUE TITLE
AD experiment opt-out not applied

### ISSUE THREAD

**Issue by xAt0mZ** [kepi/chromeEyeDropper#246]
### Describe the bug

While I opted out of the promo campaigns experiment after the first one, I still had a new tab opened automatically this morning with the new campaign.

People are already complaining in the Chrome webstore reviews...

![2024-01-11-120528_918x332_scrot](https://github.com/kepi/chromeEyeDropper/assets/7642331/69e47655-1fb9-40ee-8dff-214e2f6dd2f4)

Please ensure that the opt-out is a real opt-out.

### Operating system

None

**Comment by kepi** [comment]
Thanks for reporting! Definitelly not intended

**Comment by kepi** [comment]
New version is published on Chrome store with completely disabled onUdate campagin.

In hindside, I'm kind of glad that the opt-out didn't work, because otherwise it would take much longer to realize my mistake.

**Comment by miarez** [comment]
Hey bro, changed my review back to 5 stars. Must be a crazy day for you today haha.
Reddit post is here too btw 
https://www.reddit.com/r/antivirus/comments/17f5vzz/what_is_max_ai_me_and_why_did_a_tab_of_it_pop_up/

**Comment by kepi** [comment]
@miarez huge thanks for that, yeah it really was a day

Thanks for link to reddit, I'm not much social guy, so it didn't cross my mind to check this.

**Comment by kepi** [comment]
@xAt0mZ I finally found the cause of opt-out not working. It will be fixed in next version which should be published at the start of next week.

I'm going to do couple more tests, but the issue is clear, so hopefully it will work now. If not, please let me now.
