### ISSUE TITLE
Add firefox support

### ISSUE THREAD

**Issue by Sundewplays** [kepi/chromeEyeDropper#247]
### Describe the solution you'd like

I just want Firefox support so I can use this on Firefox and its forks, that would be cool and I'm sure lots of people would want this too.

**Comment by kepi** [comment]
Also, I'm closing this in favor of same (but older) request and I'll update there. #175

**Comment by kepi** [comment]
duplicate of #175

**Comment by Sundew-plays** [comment]
Hey this is sundew yeah you can ping me if you want me to test id be glad to help you out

**Comment by Sundew-plays** [comment]
I got new email so I am just migrating everything
