### ISSUE TITLE
DOESN'T WORK AT ALL

### ISSUE THREAD

**Issue by BuBuStuff** [kepi/chromeEyeDropper#251]
### Describe the bug

it just doesn't work. nothing happens when i click pick color. it just closes the extension. keyboard shortcut doesn't work at all.

### Expected Behavior

i expected a crosshair to pick the color

### Steps To Reproduce

i did it on multiple websites with opera, i clicked the button and nothing happened.

### Operating system

Windows

### Anything else?

very bad, doesn't even work

**Comment by kepi** [comment]
@BuBuStuff do I understand correctly, that you are trying that in Opera Browser? TBH I didn't even know it is possible.

Official support is only for Chrome. I'm working on major version, which should be compatible with more browsers later, but if you are really using Opera and not Chrome, I can't help you at this moment.

**Comment by BuBuStuff** [comment]
> @BuBuStuff do I understand correctly, that you are trying that in Opera Browser? TBH I didn't even know it is possible.
> 
> Official support is only for Chrome. I'm working on major version, which should be compatible with more browsers later, but if you are really using Opera and not Chrome, I can't help you at this moment.

yes, extensions from the chrome web store do work on opera, but thanks for replying

**Comment by kepi** [comment]
I hope this should be fixed in next version. I originally hoped to release it today, but it will take at least couple more days, two weeks tops hopefully. I'll be glad if you find time to test it when ready.

**Comment by kepi** [comment]
@BuBuStuff it should hopefully be fixed in next version. I'm looking for people to help me with testing. If you have time, please head to #256 and report your results.

**Comment by BuBuStuff** [comment]
alright, thanks. by the way it works perfectly now :D

**Comment by kepi** [comment]
Thanks for the update!
