### ISSUE TITLE
Cannot use the extension on any site

### ISSUE THREAD

**Issue by lephantriduc** [kepi/chromeEyeDropper#252]
### Describe the bug

The extension just shows the following:

😞 Whoops. Can't pick from this page
Chrome doesn't allow extensions to play with special Chrome pages like this one.

chrome://...

### Screenshots

![Screenshot 2024-03-28 at 01 43 03](https://github.com/kepi/chromeEyeDropper/assets/87744086/6adb894d-7c30-482e-9304-253e0bbd150d)

### Operating system

macOS

### Browser version

Google Chrome

**Comment by kepi** [comment]
@lephantriduc this isn't my extension. It looks really similar, that error message is definitiely taken directly from my extension but there are links at the bottom which aren't present in the original,  different background etc.

Did you install it from official Chrome store or locally from this repository?

I would be really careful, as it might contain some dangerous code.

**Comment by lephantriduc** [comment]
Whoops, you are correct, this isn't your extension. My bad. However for some reasons, your extension works fine on Windows but not on MacOS. I tried picking color on MacOS and it just showed a spinning blue ball.

**Comment by lephantriduc** [comment]
After I have restarted my Chrome, the spinning blue ball still appears but just for a short while (I think the time it spins gets shorter and shorter the more I use the extension). So I think I can use the extension properly now! I use Sonoma 14.3 btw. Thank you so much for your help, I really appreciate it!

**Comment by lephantriduc** [comment]
It only spins for like a fraction of a second now, so it does not bother me at all.

**Comment by kepi** [comment]
Thanks for reply! I'm glad it works, but it should still work even without restart. Definitely something I should look into later.

**Comment by kepi** [comment]
Followup discussion for similar case is in #255 which should be fixed in next version.
