### ISSUE TITLE
EyeDropper does not work in Brave browser

### ISSUE THREAD

**Issue by Afetzner** [kepi/chromeEyeDropper#253]
### Describe the bug

No color, nor hexcode, nor window is displayed when using the eyedropper tool
The loading cursor icon spins until the mouse is clicked anywhere, then it stops

Inspecting the developer console of the extension windows (with debugging from source) has the error:
popup.html:1 Error handling response: TypeError: Cannot read properties of undefined (reading 'colors')
    at drawColorHistory (chrome-extension://phknjgimfkldhblpdkaeidppdedhpljp/js/popup.js:2420:31)
    at initColorHistory (chrome-extension://phknjgimfkldhblpdkaeidppdedhpljp/js/popup.js:2474:5)
    at bgPageReady (chrome-extension://phknjgimfkldhblpdkaeidppdedhpljp/js/popup.js:2290:5)
    at gotBgPage (chrome-extension://phknjgimfkldhblpdkaeidppdedhpljp/js/popup.js:2280:9)
    at chrome-extension://phknjgimfkldhblpdkaeidppdedhpljp/js/popup.js:2194:9
    
 

### Expected Behavior

The hexcode of the color is displayed near the cursor when clicking the "Pick color from web page" button 

### Steps To Reproduce

1. Open Brave v1.64.116 (a chromium based browser) with chromeEyeDropper installed
2. Navigate to https://github.com/kepi/chromeEyeDropper or any other webpage (not a protected chrome page)
3. Open the eyedropper extension
4. Click the "Pick color from web page" button
5. Hover over the background webpage

### Operating system

Windows

### Browser version

Brave v1.64.116 - Chromium 123.0.6312.105

**Comment by kepi** [comment]
Thanks for your report, but I'm currently supporting only Chrome and Chromium, not other Chromium based browers.

I intend to change this some day, but there hasn't been enough time so far and might not be for couple more years.
