### ISSUE TITLE
when i select a web page in color picker 

### ISSUE THREAD

**Issue by AcAvinash** [kepi/chromeEyeDropper#261]
### Describe the bug

when i select a web page in eye dropper  a canvas appear and it doesnt close even i do  escape button
!
![Screenshot 2024-08-20 145047](https://github.com/user-attachments/assets/5d4a5233-b865-45b6-a0c7-de4068995314)
[Screenshot 2024-08-20 145047](https://github.com/user-attachments/assets/f9f66c3c-f146-4af3-a8b9-0640aef263a8)

### Operating system

None

**Comment by kepi** [comment]
Hi,

this isn't from my extension. You are probably using different one. If there was link to this page, it is probably something forked from this, but I dont' have any knowledge about it.
