### ISSUE TITLE
If you open an image (jpg, svg) in a tab, the pick color doesn't work.

### ISSUE THREAD

**Issue by pedery** [kepi/chromeEyeDropper#264]
### Describe the bug

Color picker tool on images (alone) in a browser doesn't start at all.

### Expected Behavior

Expected the tool to open. Nothing happens.

### Steps To Reproduce

In Chrome, right click on an image and "open in new tab". Here the tool doesn't work.

### Operating system

Windows

### Browser version

Version 129.0.6668.101

**Comment by kepi** [comment]
Thanks for your bug report. Problem with svg images is tracked already in #213 but jpg one should work and worked before, I'll have to check.

Can you send me example URL of jpg image which doesn't work for you?

**Comment by pedery** [comment]
You're right, svg doesn't work, but jpg appears to function. However, when you use the tools from Google image search, it fails:

data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxITEhUTEhIVFRUXGBcXFRUXFxcVFRUVFhcWFxUVFRUYHSggGBolHhUVIjEhJSkrLjAuFyAzODMtNygtLisBCgoKDg0OGxAQGy0lICUrLSstLSstLS0tLS0wLS0tLSstLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf/AABEIAPYAzQMBIgACEQEDEQH/xAAbAAACAwEBAQAAAAAAAAAAAAAEBQIDBgABB//EADsQAAIBAwMCBQMCBAUCBwEAAAECEQADIQQSMQVBBhMiUWEycYEUkSNCobFSwdHh8HLxByQzQ2KSshb/xAAZAQADAQEBAAAAAAAAAAAAAAABAgMABAX/xAAmEQACAgICAQMFAQEAAAAAAAAAAQIRAyESMUEiUYEEMmFx8BMj/9oADAMBAAIRAxEAPwD6gagama821EkiEV41W7a8Za1BsFcVDZVzrXKlCglBtV6LVFi3Uhao0awPyq88ujvKqJt0KBYMFroogrVTVjWRFSqsvUDerBCVqVCLeq1blExeK921WrVMGsA7bXRXTXhNYx4RUGqRNQegErYVTcFWXGoZ3rGPDXkVWXr0NQFNFsqQt1wq4UxirZUWSiKqeiEGNurLdqpEVcgrGIi3XuyraiTWNRWVqthVpNVmgBlLUPcWiWqpxWMAXBVDijbi0K4rDlKmKuS5VZrhWAGW3q4PQCvVy3KBgrfXbqGNyu82sYJ3V41VI1WUDFF1aDuCmJFUvbFYAABUoq9kqO2sAfKat3UKr1aHq0kMy/dVTmoNdqk3qmLYQtXJQiPRKGtZi2otXTUWNYJE1WxqRNVk1gMixqDCpVFqxkUutUulEk1BqAwC4qhnoy6tBXlrIJE3a9F6grpqAb5pjUMPNqavQNpqvRqDMH22ogNS+21Eo9KLYRUWWuVq4tWMRKVA26uFe0QnJdohWpJp79HpqBVmFqy65cqk3qpvXaHLYmp8QUNLN2jUes/YvUztX6FULQw31FnofzqrF4GnUbGUWwnfXitVG+vfMgTW47Nx2V6nUhWAq4HFJ7jbrgM013U2SCSHnFI9qJFdNeFqgTsruCg74om49CX6KChffWh9tFXFNVqlMMRWrlqS2quS1QMdZFEioYFduoCFu+vN9VFqiXrDUFi5XG5QbXqgL1EwBp71EfqKVi6BUP1GauMN/Mmp7sUu016aOt3RxTJBLQaItXq7y5H9qEuoRxQcTOIe12BQ2m1HqoX9WZ2xVoWM1lroyddDM3x3IA7k8Cu3khtpB/wAA7mA+pgDkrlcwKA09z1D7jmgb9i8NdvO/wBSiLjFYKLyBHB9TAR2z2rfkZe4x0lppJIg+xowXqGveidrllPBP1D4PzVKXKE9sWYyN6uD0A12rbbYqLRM645FWabTFwTuUR7mP6UPdq/RwJ3cEZpox2GK2V6GyLjH1AJxu5BI9q8awAcEH5FD6Nrfml7JIQ/+2ciRgn7YpgRJ9qbLBQRWceJRtr0GrmSh+5qBIjdrxKtVa9YRRAUXDQ925FXXaFdCTWGIzNSip2kirxamiBsy+oegzeq/VmgO9VbGG2lu4oy2xxFAaEZAp7a04inVmVjHRtCieauvoIoB5j/KrNQ7bMe1WdcbLP7RXqLoDYop7+BSZZLSeaZaeoRnZBSsadEu7bk5+k8R/We1ZfU37za8JH0KC/1L6ZPAPJIbnsJE06TUujSiF2j0rE59/is3a1t19eW2+s2kVi5MDZhx7zuMfinckqRS0kPtV1Bf1PkoMbdxkywPt/f+nvRiCkPXNUlvW7k3XJVVwI9cKCPvxjvIpx0++XQMZzPIg94x2qEJ+pxfuSjNOTRLfmjrZxS/bJmi0fEVRodoIGYqrq98W7YKmTkMD3EZj5onSX1T1E8Cs9estqLzG5cISPSoMbiWBLR7QB+9WxRXZXEl2M+j6YbQ6kbWHpj2pnbFQ0mm8u2EU4HHwPavFaoZnykSyyuRc9C3UiibfE1RcntU1AQpsmKIW3NT09iTNHC1QkBsXPYoS7bpxcWgLy0qMBKtEIKhViCmMY6/S6M0ePVxmq30je1UY5dpGzitDpmkCs7ZAt5cHt8GfzzT7SHaBOKbHJN0GPYfctws1dpQGSqbbi5KgiQJNU2b2wGK6LK2B9S0kNj9veqekao3t5CQFMD7xJH4OKjqdaxbgmOTGBPzV3gZDca/GAzsQ0EISIBAkc/6VzuK5qiSjcrIdQZgpAkT7Ej+1ZfpSm3q2RVJYqAq7vrdiWJk1u9fpskEcfmsulv/AM+p3gLslgSPSBIMe0+mjkjTTDOFUFeLrLWW3mFYqhG0kkOpx8gkxk+3HtbrHuNa07HYTcuKzupxuWSdwAkEwTSX/wATmfb5iCZgN3EDgzz3+RirPA7+ewcscrtQnKKqiCZjEmP3NT4+tpeQSjs0wOJqwtQeuDI+0wfkGQR7g9698yqyA34GlhAQQx7e05pDpNDcN667XOHi3IE7QBJ+cz+1S6/1LybQubigU57+Zj6SO1VeF7ZvHziNtv6rSkHcZ5Yn2M8fFPjdRqykJOMaNO2skwP+9c12KpWx6ycUs6j1ZRc8pFLvEiOO8hm7cVy5LT2Qb3sdfqPTipaUTSvQO75ZQueA24R7zAp5oUig5aCug61airCKtQYqLCgIwa4tBXkpg4qhkrGsXFKiaOe1VLW6ITFeH1Dc1oNTpwBMTAmOJ/NZLpTm28HvWv8A1Y8p8KSVIG6SBg5j3rqq4l0rRiuq9TDxv9TyNh4CjIDGPtEU36arBEUlmJE5M85gH2pV0G1Zuq6sxFxNkQvpZAS0EnHendvVBbikDg1zYcdPmyWOL7YRqnFttu0rcIwQe1Q0Wrk7TzTfXKjutxhBApf1jSpbKXAfq5FdXFp2Wlp6I3NE4B1AIZLZDPa7soz3xOOKN6R1BXaQQQV3/wCBYJJEKBhiCf6VZ0fSC6GLMCkQVz6jEjPA5q6zpdMHBtFrZggKD6ZjkjmYj9qeMUm2WhVM9ZlMxx8/2rEdYup+r2su2fLRj72y24n7dvzWs12pFpXd5MST7mBLfcwCaQW9K2o11oxFoorEkqCM7lWGOTjge9Sz20ku7JZbpUE+KtOblny1CBbspvdgACcg5wAAJMnPakfQv4N4KtxSBbCLsBhhGGHsCMz9vbLO54ceb9s3FdHMi3tabZM4nJYxHxiMU06KNKjqsW+wB2+ouoVRtLY9/wB/ii8cnsKg2gPg0S3OKp6x/DuMBkT3ABzntihdPrRI3ECePn7UNIjpdi3xlc3RYPqDKjbfkNJ/cAD81q+lbltoHADBRIXgY4FZzSWfM1t25cytpUFtewJyWPv/AC/vRnXOqG2o8tlFyd2cgW1Es2Ofap8lHZlt6HYusynynXfvCjdLCRllO3jsPzSrR9J/T7gw9bks5yZY87ZOBzirPD2pRrLOoYbmLA4yxPqJH+dWi81x5Yyff3+fv802RKk/I2Wl+xr0y1im1lIApdocU1tsCK5mRTCLdyplppbqrj7gicnJ+BVu+OawWtFtyq2aKi96gdXqM0UKMAarK0Npr01d5lYx871VorcBiQKYnWTacFJlSBkiMc4q3W6EPEHJOB3/ABSjY0y/pNq6Q4mBG0wW++MfNXlOkyvPwB9CvLDRO6FEkydsYH96NtXPUKfdJ6FY8pnKwbgkOn1YwsqYxGce9Lf0wDETJHehGMkkgxg0tmi1Gw2l34kVk+v6htyqDIGBWm0umFy1FwExx7zWI6ve2PgECcd/61TLLSRsng2fREK6YuEubhJlmKq8j+ReJwBNC9D1HmncVZiJMxO3BUQByRkfYmhr+tR9ABuDtOQCRtg7gWx6Y94PHegfBnn7i42kxnbneM7efjbxHFdMKUTshSgEePrv8FNhbcSYgm6AYgEhQQo79u4pVodZqLN+2bIbc4tDYvrgkbSNvyBzHY066nqtRbUFLbABiXIIU+WT64VuYBY/ipdK67atXVZ1DPchQVUZBJkD/B2wPeufLBPd0QyJOt0D9ZvIr3QbhW5kbQ0ksUYjnmNvIxg174U1JvIlp7cOACt0gAM4UfTHvNL/ABoCbj3jMoIA2QUt9wrT6hiD7bjzUOma9LOmtNJBc+nkmTxH4H7U7nTpjylxWx/rdGc7jJ/es310hDaEHduDL8AEBhH5rQaTVi4V3tA7mh+u6ANqba21NxLRDuWgBlJ9Sq2Ow4PNJOPJaOdw59AHh3TW7movNcdhLFQAN0hRDNJMACAPxXXNBat+YslwG2gmdxVvUQT7cYHtT29q7JYsLRRlQgOoi2FaDBxDNjjNXXNXbtWmD21uBzI9IwTzQeFcbfgpwqLYl0urFu0FTjt8DvR2iujms+FaZ2naT3GBTbTW3A3FSF7HtXOm3Kjmtt7NJp78UwsaiBJNZnSX5/NOrZUKAWkt2/1p1DkFRt6LNNe3szq3fH2q99QDSu4208AfaqG1VCarQZew1bUUu1GqzVV3U4JoYEsgPvSqN9CpDbT6jFT/AFJpZpmIGasa5Wo1Fur1aW9bbcCE3BOMbmmdo+wFZ7xhonXWXtzKUum0T7QsmHjPCnjtVni/RkhboZ1KsrQxXazbgFIUZ+5xUvE9gMw1DXVhLBMHcSbm4hIjt9WT7VWcNyXyVcfU18hOm6gLl1m3SqJiPpO7gx7QtLbesHmTwKl0VmtaQShLOSzNH+LtPcClT3PVxjkxQ58YpsMb42zZ6LUs6MFMEAkfgT+Kz2s6W94SGAAyZGcc1DZNq6291ITcAvcDmWGRXnTNBq2QqqPPAY4EEyCSMTBoZdzT/Ak1b+A/p/Tkt6d3lj6ZIXLGJjavc54pH0K9dt6hbuptm2zIotFW9DbcMIn03G5I+KfqH0cpcMGJnsfzWVu9VuNq7FqVRCwLOdpRkJLF/wDqgEfBz3qsZcUk+xk1FJPsJ8aeJw+pV7Ny2bdsgXwZb1RBA78AiRNeXr4s2FO0s9v1iWcNEdmBkH9qX+Jr1oa5LmwC3au7bihRJCKLguT3B3DEdjWg6Tbt67UPuB2qARDqoPwVYEsOPt3rO3+wOTlpFN7WWL1l7tx3DMgVUDHaQpXcHA7NnI4xSLTE3TbP8lpFA9jcZRuP4ED8mu0WjayNWhYMbdm7tg/SZyu3twPvNPug6E+aunwFt2Va97m7ciFnuQAf2qbc5dmblJVL3K9MxAgmKN6T1hVubCzsrvB2gGSJPq3Cf5f61DqmjCXQFJ+3xQfTOpC2H3qm+WdAqw7KMMY+8j+lDC2pJMMFxnQzu9Z893BGxFJXZOAIJV+O88Uz1Ck2lUwQMgwQVntQGgtMbq3jO6AJgfzAHaw+J7006/duLds2Qk+crFSPccgfNdWSXppl5u40yPUNUj2EVYAAknjPAFUXdcWsBIOO8Us1nTLlpgl+F2pKqD89470dpNQG04E5/rXNGTbp+xypu6Z2l5ozo3UvNmFwpgtHf2FLtTd8lNzcGRn7U68O6cLpkO2JE/JnuaHNp6F5NPRTrb2aWkmaP14zQmwzS9hQZ1TTr5IVeWgfvVr6Ly0UVRbstccGcL2q/qN0llBOK6kktl0ktnNbMVQ1s03W16JpWL0SKjOLvQrg3tGY8U9TJUOsll57hd3b5EA0Po9Z5yncJVAiKwBC+hfpzyQWai/EF9byWG8rb6FgZbC4V7h7/OKt8MW/Osi1scjdJa2m7aXYk7xgD96Rpym67oRJtt2MbN4JZIyZEcnbjiBwKY+BtNZa3cNyCWMAESI+3egL3SbzM9q2CUSArkAecYBPlrMmO8f1oXo/T202qRbpZdwJhiUHNUTtq1+Cjk7Vhvi3rdm8f0tpVLh/LLG2US2CrBycZiFNEdF6wGsJaVywQBRcHDDOAP6z81leq6Hdrb9tS7EshTbMhWEOW/tJPcVotP0r9LpSbg2vJIgiADwJowk+TbXQmOUuTbG2sYXlO+GgQMZ4r451XStbuuh+kTtaDhWwQD2gVqv/AOhdCQKzniBxeB3Ha2CJGIOMmJGRU8mSM6aFySjNWFdQVL2uS0qkrtSWnBRVw0jkEQPwB9jEHk3j5bEKZ3DkQfg47ChOl6lhfsQochgtpcbmDG2yBjGEy3/1FNPEl4PfcHfILCGcvtzlQTxme9NLcLXYFuNrsC1+q323uFocK9tgBG5TJkmefp9/p+cbDoVu3Z0y3jO++xe4xnEkhVA9gAP3rEamwblpkGCFLn52fP7GtV0Tq9sNYsN6x5NsrPHqAyfn/Slwt+SkXrf9oY9TUNvYEb7ahmSDO1wdp+eKy/hq5aW2bl1H81rgshshhAWCo575J9vimvjAul4sDAuWjbxAyASnf5NJPDWjuFowEst5jnkeY6AC2p/mgTmmTrIBWp3R9E8MaMW1LgywEScx2n5OKXdXuebqrdxtwFoSoAnfc9W6G/lEbZpl0C5cNklFMHv/AM7Vmen9Su/rGtgLBZvMbhYxE/P/ADtXQ2tWW5JJWOvGKNdG1QCQkwMn5n7Uu1dhLVq2oMwAS3Y/ejrrCzcdfNDG5M53QvcA9qq14tPZO0Qe0f5UHj7YHBN2G67punuLba5cwsEgdz/pTS5dXaNv0xisPfu3WNtVRoJEsfYYrSarUqqCCTipziuNk8kVWiOoYVZc06raLk5pK2try/rSybN0AmpRkvIipdjfpagKTP8Aw+1Q1CyRjNR0lqFie1WXrkRAqsZchlKw29K2ppJYugzjPyKc6i96VB70A+wHBNVx7RbG9Gc8WXEuW5tDbcR9jqsqm0kAsqg4BzxTTwk9yw5ZUlSAT6SQkcnAMCkPjC8gvoFaMIIj1d59QyTIwD80y6D1V3c2xGwDcxJJ3R8TFc3Jf6NEpNWX6PrbLqSRdLDlC3buwUdl5gdhRfi/RNfUM21ZlgFwZOQTHz96yF0OXtFJI3sg4xtAZp7cfNafrru2mBkg8ZMQY4imw8pRambHck4yM+urus0hiDdS3JVjKqs7/tkxj596d65nuKEJPl7Zk5mPc1meh9J1zItxLbm1tIcqIEbsbceqM960ltns6TzAQytKGcQeCIPee1Njdqn2HH9jsA6Zp7e8hoPt7D5FT6v4ae9Zc2lG9N2yTBZSPUn2ODnuKVPqCoVh2rV9I1V42C+3BHvmKTC4yVPwCCi04s+aJ1VU1FlrgLi0rI4BKxtUgDcMg5zHzFbbxBYtlbd1U2B7aFR8REH3OM1j/HWh8q4rgk+cCYxCusDn2O4U2/8AD7xIz+bp9QhuYDW94DBAMXANwIEkqfyapBJKmaktEtBe9TQIZVgR3V9oJ/vRnhTRIyF2zctxbGfpW16VGPyajbtA3WIRghJCg4GTOIgRij+laYpY1TJAZWuwf/kJYEj81z4tyYYxbjb2Z/reqa2Htt6hMoxmFVpMfcer8RT3wLZHlahpP1KgYj+VVEkDvzWQ1943TukFggBkekEgsx2+/wBImvp3hzS2rWkRmeEiWzGSZJE/k02Dc7Exx3Zf1TU3rSJY077jcQjCwRMACQeck89jQvQOjJZS0u8B2k3FuAkzwdrjvxznFea7qQMAKFUGFaNrbiBtYAYOGIBxzUk1dt7uxj6rYUu2QTu/xGT2rtUKdnWoV6inqHTEN0rZUAsuxiDIkTnOaVPfuadksz6xzPEdqD1+udWI0zbne4wG0zCD5NA9RGoR1e99fA/NTclapEm/Vo1+i1rEncQ/sB/Wrbu65CgR70o8OW/LQvyfmnH68mIFUmuSKSXIWdQ0ptnmlmpYgqR78U26rdZyMGhR0y4WUmCOSB7e1efODctHJNbaRoLN+FEntQ36yY+DQ1zzCDCNAiTGAD3ND3LLbCwMAf1+atC7DAOu9RDgj2n96r0+qAGaA0EKkmSzGq9QxB5FdKfGNl74xPeo9K8vVpaf+IDBulJJ2tg7CRz+Ke6/w+ultEae3edjnedphAMqYGMGilt2rl+HVZDny7ker0xz7ijOs9TvAi0HHqBBeMR7fBqS+nSsZYUZTSeDLtyzbu22X1EteVnIwsFfT/iMR+aCfqhvOib2QI7WypG9uA24dpwB9qadc6ilq0CGa1c/kjKuEyA4J4+0GsRq1u2dUFW8J3C9vAiC4DOAOCMyPxQlUNEsnpaS+T6v0qxc01khnIT0C2u5ixQKBkPlSTJg+9Zvxbob19P/ACt4BGK+bp2Gdw/9xT9+eKI1nUWuWkuXQwUlGBJElCdpeBwPTj80qu6HVWLh1LFLiN9JRphZgAgx7jias64lpJcUvcTXOlXli2cH3PEVpNDcuWrPllpnuOKUa/WXXuSPbI5ihW1TjDEmfauOLjjujndQsX+NlHmWlALLctblYnKkmCNvYzGfmsz0/X3EbzFWNhVC08c4M5M7SPxWou3ANRaJ3FUOTxAHqMH8GP8ApNU9c0lh9Xau20C2NTJJMgbiYkifqkjPzNaDU42Ti+dml6l1lXFkBdqwCY7EQXU/Iq7pHUrVkaksTt8x2+8hQon8j96zi626Yt6iAbZ2MfqLlBGGHLwI+Y/ZdZb9TqWNidrkHaREsQu4D4lZPxSxk1J0dGPUGr2GdKtG6xBG2GlhIETkIR39+Ow9612lvKuoSxdQuFQNbAMAvBMMsHdWd1KPbhbjjduYzEZJkk0VourrbZrrepmaAxzChTAAMYMEmjiajKmQg1yoZavWkEuTJnccblXdG0x7GBmk+j6gb1zUXbc2942bPTgiZIKgTzEkT7020vV7VvTNqrdsKzzKDlgZAmZgAR6Y7mazdgSpZBsE72gQo3nCRmPtV8uS9JlMmWw7wh0TUXH8xCqqsqJPL+wH+dd1ovvVWYs27/8AJIMfEim3h7XtbR7aKodhuD9yQYA+OaaNqbfkh9TZDsvEHIJOArDkfFaMP+aobguGmD6LTP5M1ZaeGUfvV51ZZIiP8vahNOPUJOferQVIpFUiXiG7tWRXvSdXca4iQADmWwI/52oq/og6l8EDgUBY6jbusAwjb/cVJJ8rIxXqsc9fs3XuDYQgVD6UMB59x3oY6c3NOWJjGf8Aeo6Xq9tCdyglQRJOT/zirupqg0YdXgt2Hz2qsopOy8o0ZzQJLepsDgdsVDVsSxI4qzSlVXb3oUMROf8AapPpEZGmuMHuqzSNpJWAR9Qgr/tUOo63cwQAhCTu3HIbtn5oIdad7lxoSEkbCwA38rDH3H96z+r665um4ACgAaOCBIDExyRxXRKairZ0yyKKtjvxzrWNryHtiFClWI9yB6T+Yqvw71lxde75C3XaypU7AxtsvpKjHEDmYpNrteWUXS5l2uQGMgBY2jH/AEzP/emvRLtq1ormot3bm8/w2ELskNLIv8xME5rl5OWR+1HNuU7XRDoPULt+4VumUI5x2LMF/En96vVy94aRbgueokGIC7QSd3tg1V0PTouotqpYFw7jepg+r07QRGVB/c/FR8RaXyHN8Qh3oFtr9TA/UN38oj39qa3w+R3J8WvYfafptpFui638Q/SyH9hWf6l0o2iu6QWOO89/xU+uatYVrYZWEE/P3FV3r1+4ULiQBIPH34qGeSpxSEyNSVCPqt7uAV2knP8AhOP9f3qnqOgnTWSWYkMAABO1J5URzxxTW7orLX7aXvNRGMNtidxkLyCCJkYB4NEdTh2NlGMWM27sAyVEesL9xniRS49Rt/onBad+DE6vVOztbUMWZyp3Eg7zABj+U4J/Nbbw/wBFfS22vpcXasJuZlO52AbahGDWM19tRffafXu3STmf/iFER6p/FO+g6hltqrkG2C5VZMBmGXI/emUktoCnWl5LtZrDdvFrgjE8YJI4HtMUPq9tx0AMYDbOCCY2yR8E4r3qN8NZKBlDB2kgQGECCs94P9aq6TJuLJGAABAExxJ7moVTItu6H3iPp72bCOSoDwGTknHP7026X04HpUlQzmXI7/VIn8Uk8avcYWt5zAGPpAoQ9bcWWCtCZRQMSojJ/NddRhJ/ov6Yydl/R0uv5l+Ctq2IaO47gDvWq8M60Np32oLijBkDGMGTyftSXovU7a6P+MhKAnvAYfMUs1XXjbGzTvttuASoHA9mqkWoR2WclCNs1vmqLTXJEcR3pVoL5ubmAP37VCzrLbounVPU3qZz7RNNr2ntraOxCkCJHc+1Fera6NBtq0WWndbGTluPge9edPKW9OyhAzGQGInJ7mqNZoriaTzCwJic8/FK+m9dvjTMWxtkwRB29uapHil+RopV+R9oNAl5XDcrDExEx2Wp9aFramxvSP5e0ihNNqmbS+c31QSApiAePvSnp3Uy1vyjn5/2rTkrr3Gb3RRrtQA2PzFCW7053RR1/ppMtB2gZI/1qFnwnfuqLi7QrZAM8VzSjkukiDUvAh0+vcFiJUAy0jvMGe+Ix7VTbuQGDAZMyeIMkz95FUm6RJ3AgzMkGZj+sd66zbWQhklpXHPsOP8ApiuXk+NM5edri/YY6m63lIu8MeZ42SQAvz/vV+q0KCzaJvBWRt2yZ3An1KFHfk5pQNP/AOnmIJU+/oMhj9qhfQFDuyeTOMe1PGW7KQlJKjcdO1l13tG6RaQBdrsN0IfSvGQfQTHsfmiPEvTnUG9qCrW/UNvMjgMPnvSrwfqDdUWbqqRsneR9K5CwR3E/tSrxF1FnVNt8uvG3hY9xXZ1GzpnJRhyLum6ze622E+olmLQNvAAjgQKcnSNc1hGnVRaAUeYzQq4hpLe0j3zFZ3wyjtqbQtW/MIYEoBhVH1M04gTMmtf1T+KL11XWUm0E+kvMliQDkoNxGOT9qhjhzj8iYI81YNq/D67Q993H8QhfKhi4YA5ZjLTkiPf4r1rqaqBYsJadN6KoWP4axtDx/MDPq9jmmvRNmo2LdJUKsllOzdKlQVznDH7fk0w0GhtabVF7EbWG2CSZJ55q3+K6iWeJbSPj/UtNdfXFGtNafblO+FLGe0GiUuNvbdIhQp4gTgQO/fHxTjx5bVeoM9skEqIHCifqAgChOlrsLPcEQsWycDOSQp7/ACahKFzpeDmnBOevAqJJZgTgE4OeOM12wqw9RExVT3SGY+5qi5fcmOPaoVshJIedbwUhmYFYk5AahVsegbiYJMD496u1JU27ID7ifqHAH7UDrNczQFOAYA+PerTW2M0n/fovuO3khSfTu9IHsOSaY+G+leZqQz5TBO3OOwzSi4pxu+T8VqvC+qNmzvECcKYyT8UcfrmkUj65KLH9zp+zVPfYJ5UAKe4gR6h2NRfr6iSACo4Hv8xSLqXUblwizbtu3O4gEyTk/sKsveGbqA3bm3btgAMJA+R7108q1FHQpVpEm68Xw/0bhMHtV3V/F9mWQKIgKBGWB5rM6dpVkUerdyaCOnHnDd279qms0q2Isjo0mu6m62SgwCcDiB2pfpVcFdiye+ahq29M8if7U06a21S7Hn/L2rW5TszTch10/qFwJsYBUbBJ5P2rzU6x7YVQ8DMfahrim4QTx/KP7VX1PVtIUrEDv+K6MjqNnQ6ow9sAPBGRInn6ZAj34HNEabWKCDsnaAWkkBn4mB2+Jrq6vNUU2eavIdoOlPdsnU79u1iCBgzPIgUD0/Sm+3liBvO0TkATJn8A11dTqCtFYpXEb9R1ltbapbQobdsq7AwXyIJj8/vSG36gTiYmurqOZuzfUd1+Bl4eN3zUWy/ltcYKGiYIO4GI7baZ6FQhKxu9ZD7shy8Gdvt8V1dVPpmV+jemv7oeeHtFaFu61w3H3MAMgQFMjA459zRvUNJeuqwt3RadfpYLIj7e/wA11dXZFUqOylGOj5g/ULj3TnCmIOSWHJP3PavOr9QuXCNx4FdXV51u6PKyyfJoFCFiiExuIEjnNWaiyAWEmASATzA968rqk3Tog29HC8B2nGPirbFoEiurqyY8ZOl/ewXeMvsMxgCK3F0fptlhgHQAHb2BPcV1dXX9GlTOz6ftg56wdKGvKiyxnHbsAPihrnULtxDcxDk7hJ5icCurqpm1FpBytqLozq3yCzD70tbVEmTMzXV1cEZPo5k/SgnzyyqK2DdP2WkWct39q9rq7sSu/wBHXEpS95Kw0sQeapua5rrFjHaurqfL9tFHtI//2Q==

**Comment by kepi** [comment]
Thanks, I thought that might be the case. It is also known issue (see #189).

Both cases are in fact same. Chrome doesn't render any HTML around such image and at the time I tried to solve this, I didn't find any way to inject the javacript to such non-page.

I'll close this issue as duplicate, but I'll try to do some more experiments when I have time and share the results in linked issues. If you had any ideas how to do such injection with current browser API, you are definitelly welcome to share them.

**Comment by pedery** [comment]
Thanks. Here's some info that might fix this:

https://stackoverflow.com/questions/8499633/how-to-display-base64-images-in-html
