### ISSUE TITLE
Feature Request: Export all or selected colors to PDF/RTF

### ISSUE THREAD

**Issue by xgravity23** [kepi/chromeEyeDropper#28]
I want to be able to build a palette from a website, then export all of the colors at once, instead of having to copy and paste each individual one. I'm not really picky about the export format--even TXT would be okay--but it's really important to be able to export all colors with a few clicks.

**Comment by kepi** [comment]
I will definitely add option to export to CSV (see also #86). I think it should be enough for now. Maybe in some distant future I'll think about other options like pdf etc.

**Comment by kepi** [comment]
CSV Export is now added in 1352c66fe031ed98a35252399cae68b2e8373d0c  (version 0.4.0 which should be in Chrome Store in about 60 minutes).

I'm planning to add more options for it but should be sufficient for now. Sorry it took so many years to implement :)
