### ISSUE TITLE
pick from web page as default

### ISSUE THREAD

**Issue by mxtbcca** [kepi/chromeEyeDropper#38]
Would like to be able to set "pick from web page" as the default behaviour.
Once set, clicking the icon would automatically select the colour picker cursor 
and let you select from the active page.

**Comment by JRichmond27** [comment]
Was this feature ever added? I just downloaded this extension in 2022 and was disappointed to see that it requires an extra click to get to the "pick from web page" behavior.

**Comment by kepi** [comment]
No, it wasn't. Tracking of this feature request is in #18 this one was closed.

There is keyboard shortcut to do exactly what you want. I don't intend to implement anything else anytime soon, as most users are using color history and doesn't want this.
