### ISSUE TITLE
Doesn't work on GMail

### ISSUE THREAD

**Issue by ahmadalfy** [kepi/chromeEyeDropper#49]
No matter how many times I click the color picker when I am on Gmail, it doesn't seem to work.

I am using Chrome version 27.0.1448.0 dev-m / Windows 8

The console gives this error:

    Uncaught TypeError: Type error
    image.onload

**Comment by kepi** [comment]
Eye Dropper is working on gmail without any problem, not sure if it was fixed in some previous version or with change on gmail side.
