### ISSUE TITLE
EyeDropper color picker not mapping to retina screen OSX 10.10

### ISSUE THREAD

**Issue by bethalex** [kepi/chromeEyeDropper#77]
Color picking from a website is not working on OSX 10.10 (Yosemite) MacBook Pro mid 2014 with retina display.  Color picker doesn't seem to be mapping correctly to the display -  colors shown don't match what is being pointed to on screen.

**Comment by kepi** [comment]
Finally got my hands on Mac. I'll try to look into this issue this weekend.

**Comment by kepi** [comment]
@bethalex @heartrate160 could you please try it again with recently released Eye Dropper? I tested it on retina display and it should work ok now.

**Comment by bethalex** [comment]
It's working now for me thanks!

Beth Alexander Designs

Web  Site & Blog Design, Social Media Marketing
http://www.bethalexander.com
Tel:  831.704.6684
Mobile: 831.246.0634
Contact Me <http://facebook.com/beth.alexander1> Facebook
<http://facebook.com/beth.alexander1> <http://twitter.com/cryztalvisions>
Twitter <http://twitter.com/cryztalvisions>
<http://www.linkedin.com/in/bethalexander> LinkedIn
<http://www.linkedin.com/in/bethalexander>
Chat [image: Skype/] cryztalvisions,

**Comment by heartrate160** [comment]
Its working for me too! Thanks so much!!

**Comment by kepi** [comment]
Great news, sorry it took so long.
