### ISSUE TITLE
Click Extension Icon and Opening the Popups was extremely slow

### ISSUE THREAD

**Issue by bjmin** [kepi/chromeEyeDropper#84]

**Comment by kepi** [comment]
Can you please provide me with more details? How long it takes to open? Is it only on first try and next are better? What version of Chrome and which operating system you have?

Thanks

**Comment by kepi** [comment]
Popup is now completely rewritten. Loading is much faster now and should be always almost instant.

Fixed in 0df8a125f59c4621f8c970730c6bcaa16e1275b8

**Comment by bjmin** [comment]
Thanks! sorry for not seeing this issue before...
