### ISSUE TITLE
Chrome forbidding "pick from web"

### ISSUE THREAD

**Issue by DiGsInNY** [kepi/chromeEyeDropper#85]
Chrome is not allowing me to use the pick from web option. I get an error stating that Chrome doesn't allow extensions to interact with special pages or local page. How do I get this to work on those pages?

**Comment by kepi** [comment]
Unfortunately you can't use it on special pages (like config, chrome store etc). Its Chrome extension restriction placed by Chrome itself. Same apply for local pages. I can't 

If you see this message on normal page, please let me know its address, I'll take a look into it.
