### ISSUE TITLE
Mising Input Field in Color Picker

### ISSUE THREAD

**Issue by devilzk** [kepi/chromeEyeDropper#90]
Hey!

I like the new changes (seemingly just a nicer interface on my end, but I know you've probably put in some improvements) - however you've taken away the input below the color picker. Are you going to return it?

I often found myself putting in hex codes to retrieve the rgb code and to add slight variance to my color by moving the color pickers slider.

If it's still there and I'm missing something, apologies. Would like to see it return if not though, it was handy.

**Comment by kepi** [comment]
I was afraid it will be missed :)

It was totally unintended change on my side. I'll definitely return it back.

**Comment by kepi** [comment]
Just published new version with input field returned. Should be available in about 60 minutes.

**Comment by devilzk** [comment]
Thanks! Great to see it back. Very helpful having it when you're working on a site.

It seems to shake the window/extension page popup when clicking though - just me?

**Comment by kepi** [comment]
Nope, same (or similar) on my side. But it will be little harder to fix.

I decided its better to have input field with little glitches than waiting for it couple weeks :) Created issue for this in #91
