### ISSUE TITLE
Double color picker when selecting palette color

### ISSUE THREAD

**Issue by devilzk** [kepi/chromeEyeDropper#93]
Selecting a color from the history section within the eyedropper screen, going to the color picker screen, returning the eyedropper screen and selecting the same color or a different color from the history section and returning to the color picker screen results in at least two color pickers appearing. A lot more if you repeat this.

![image](https://cloud.githubusercontent.com/assets/21030742/18143915/19bbe8ec-6fbc-11e6-9cd7-8e4a456f4cb2.png)

**Comment by kepi** [comment]
Thanks for report. Problem is fixed now and will be available in next release (0.4.3)

**Comment by devilzk** [comment]
No problems, and thanks, glad to see you active.
