### ISSUE TITLE
 Whoops. Can't pick from this page  Chrome doesn't allow its extensions to play on Web Store.

### ISSUE THREAD

**Issue by sdancer75** [kepi/chromeEyeDropper#94]
Whoops. Can't pick from this page

Chrome doesn't allow its extensions to play on Web Store.

Version 0.4.2

chrome version 53.0.2785.116 m

**Comment by kepi** [comment]
Thanks for reporting. I hoped that the message is clear enough :) You simply can't use extensions on Chrome Web Store pages, its not allowed by google. Please try Eye Dropper on different page and it should work without any problem.

If you have idea how to better phrase this error message, please let me know.

**Comment by sdancer75** [comment]
Hi

This not the case, I mean it was not a google store web page but a simple HTML page I created for my newsletter.

G.Papaioannou

**Comment by kepi** [comment]
Ouch. Can you please send me URL of your page? Is it possible it was on something like file:/// or it was public address?

If it was local file:///.... problem is in wrong error message. Unfortunately same as with web store, google doesn't allow extensions to play with local files.

If it was public address, please send me URL so I can check what might be the problem.

Let me know anyway please so I can fix whatever is wrong. Thanks again for reporting.

**Comment by sdancer75** [comment]
Thank you for your interest, but now I can not reproduce the problem. Maybe it was a temporary Chrome glitch.
If I meet the same problem I will send a detailed description.
George 

 
      Απο: Kepi <notifications@github.com>
 Προς: kepi/chromeEyeDropper <chromeEyeDropper@noreply.github.com> 
Κοιν.: sdancer75 <sdancer75@yahoo.gr>; Author <author@noreply.github.com>
 Στάλθηκε: 7:13 μ.μ. Πέμπτη, 6 Οκτωβρίου 2016
 Θέμα: Re: [kepi/chromeEyeDropper] Whoops. Can't pick from this page Chrome doesn't allow its extensions to play on Web Store. (#94)
   
Reopened #94.—

**Comment by kepi** [comment]
Thanks George, I'm closing this now but feel free to open new issue if you find way to reproduce.

**Comment by alik472** [comment]
@sdancer75 You can use VScode or ATOM live server, then you can use this extension.
