### ISSUE TITLE
Feature Request: Automatically Copy Selected Color To Clipboard

### ISSUE THREAD

**Issue by epic-kaso** [kepi/chromeEyeDropper#96]
Hey, I think it will be really noce if as soon as one selects a color from the webpage, The plugin copies the color to the current clipboard, it save a lot of stree of opening the extention again to copy the selected color.

**Comment by kepi** [comment]
Hey, thanks for suggestion. In fact this should be default behavior. It isn't working for you?

It is first checkbox in options that should be checked by default. If you have it checked and it isn't working, please let me know and I'll try to fix it soon. In that case please provide me with details (at least version of you Chrome would be great and operating system).

Thanks

**Comment by kepi** [comment]
closing as it is working and there was no feedback for long time

**Comment by dssagar93** [comment]
This functionality is not working in Chrome 70.0 . This feature should be there as it could save us a lot of time !
