### ISSUE TITLE
New Feature: Allow Picking Colors from Local Files

### ISSUE THREAD

**Issue by kluhman** [kepi/chromeEyeDropper#97]
For example, when a PDF is opened in the browser, it would be great to pick a color from that.

**Comment by kepi** [comment]
I will probably never implement this feature but I'll leave it here for now, maybe some day.

Problem is that Google doesn't allow extensions by default to interact with local pages. If you want to do so, extension must be reviewed every time there is new version manually and it makes releasing new versions slow and painful.

**Comment by kepi** [comment]
And here comes the **never** :)

Picking colors from local files is now possible in latest version (0.5.7).
