### ISSUE TITLE
I can't use eye dropper on Discord?

### ISSUE THREAD

**Issue by NewRoblox** [kepi/chromeEyeDropper#98]
I've been using Chrome Eye Dropper for a longer time, and it did work on Discord before. Just a while ago, I tried using the tool on Discord and it didn't work. The mouse didn't even show the “loading symbol” near it. Any help would be appreciated.

**Comment by NewRoblox** [comment]
! -NO HELP NEEDED, PROBLEM SOLVED- !

**Comment by kepi** [comment]
thanks for info :) glad there is no work to do ;)
